### ISSUE TITLE
Scheduler UX is incorrectly fix the height too small.

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.AdminExperience#1024]
@mathisjay commented on [Wed Jun 26 2019](https://github.com/dnnsoftware/Dnn.Platform/issues/2872)

![Capture](https://user-images.githubusercontent.com/1585717/60229488-1223d300-9864-11e9-8590-52ecd2f47533.JPG)
![Capture](https://user-images.githubusercontent.com/1585717/60229704-31226500-9864-11e9-94f2-55e549a21fba.JPG)

---

@mathisjay commented on [Wed Jun 26 2019](https://github.com/dnnsoftware/Dnn.Platform/issues/2872#issuecomment-506134672)

The skin is nvQuickTheme.  BootStrap4 based.

---

@Tychodewaard commented on [Mon Jul 15 2019](https://github.com/dnnsoftware/Dnn.Platform/issues/2872#issuecomment-511496231)

@mathisjay Are you sure, the theme is NVQuicktheme? What you described, I can reproduce with bs3 but not with bs4 (also nvquicktheme btw)

---

@Timo-Breumelhof commented on [Mon Jul 15 2019](https://github.com/dnnsoftware/Dnn.Platform/issues/2872#issuecomment-511496305)

I cannot reproduce this in my own Bootstrap4 skin.

---

@mathisjay commented on [Mon Jul 15 2019](https://github.com/dnnsoftware/Dnn.Platform/issues/2872#issuecomment-511500740)

@david-poindexter pointed out that it actually should not be relevant to the skin at all since this is a PersonaBar item and the PB runs in a IFRAME outside of the skin's CSS.

---

@Timo-Breumelhof commented on [Mon Jul 15 2019](https://github.com/dnnsoftware/Dnn.Platform/issues/2872#issuecomment-511502676)

@mathisjay  That seems logical. But as I posted I don't see it using my own custom skin.
Also the height is set to "auto" when the sliding animation is done, so it's weird that it's cut off

---

@mathisjay commented on [Mon Jul 15 2019](https://github.com/dnnsoftware/Dnn.Platform/issues/2872#issuecomment-511504971)

Ya, I don't understand why it is being fixed to 497px... I have to use Chrome Inspector to comment out that CSS rule so I can click the Save button...

---

@valadas commented on [Mon Jul 15 2019](https://github.com/dnnsoftware/Dnn.Platform/issues/2872#issuecomment-511510245)

I _think_ the height is calculated using javascript then injected inline by the code. So this may be browser related. Can you please add Dnn version and browser/os used so we can test this @mathisjay 

---

@valadas commented on [Mon Jul 15 2019](https://github.com/dnnsoftware/Dnn.Platform/issues/2872#issuecomment-511510413)

Also, I gonna move this issue to AdminExperience since the fix probably needs to be done there

**Comment by Tychodewaard** [comment]
@valadas It is not a browser thing.
Using 9.3.2 and Chrome,(Versie 75.0.3770.100 (Officiële build) (64-bits))  I can replicate the issue with a BS3 theme, a BS4 theme (nvquicktheme) does not have the issue

**Comment by valadas** [comment]
Hmm, in _theory_ the theme should not affect that, this is odd... Anyway you could share that BS3 theme?

**Comment by X3Technology** [comment]
It's happening on the .org site, which is using a BS4 nvquicktheme...

**Comment by X3Technology** [comment]
the .org site is 9.3.2.  I'm using Chrome 75.

**Comment by X3Technology** [comment]
Just tested it in Edge and it is working as expected there, although I notice a slight pause before javascript is resizing the panel to the right height.  

Seems like the easy fix would be to remove the fixed height thing and just make it auto. Not sure why you would ever want to use a fixed height there anyways.

**Comment by Timo-Breumelhof** [comment]
Strange, I cannot reproduce this in either Chrome 75 or Firefox (on the community site).. 
I just see height: auto at the end of the animation..

![image](https://user-images.githubusercontent.com/8999382/61240573-d634ad00-a741-11e9-9d89-9c77d76dcc7a.png)

**Comment by valadas** [comment]
It was probably done quite some time ago before flexbox was a good option, see the examples here:
https://css-tricks.com/using-css-transitions-auto-dimensions/

Two ways this can work properly is calculations with javascript or flexbox. I think we are now ready to move this to a flexbox option.

**Comment by X3Technology** [comment]
I like the flexbox idea.  Move to current standards :)

**Comment by valadas** [comment]
I have assigned this as an improvement and for a possibility to migrate to flexbox in Dnn10. In the meantime if this is a blocker, ping me up or give me edit rights on .org so I can take a better look why it happens on that specific site... I cannot reproduce this in about 20 Dnn 9 (various 9 versions) with very different skins...

**Comment by X3Technology** [comment]
thanks daniel.  its not a blocker, but i cant reproduce locally using the same skin that is on .org.  the skin shouldnt be the problem though since the persona bar is inside an iframe.  weird.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by valadas** [comment]
Just out of curiosity, are there other persona bar modules in this site than the standard ones that come with the platform ? I am wondering if so other css or javascript is causing it since the site should not affect the iframe at all...

**Comment by sleupold** [comment]
AFAIK there is one from Stefan Cullmann (Sitegroup editor) and one from WeWeave (Jan Jonas)

**Comment by X3Technology** [comment]
Not on the community.org site.  Just the vanilla installation.

**Comment by valadas** [comment]
I am in and I see the small pause but it does expand using Chrome 75.0.3770.142 on PC
Then I got an update to Chrome 76.0.3809.87 and still works

Can you try a hard reset and let me know (open developer tools, right click the reload button and select Empty Cache and Hard Reload)

**Comment by WillStrohl** [comment]
I just tried to reproduce this issue on a clean instance of DNN Platform 09.03.02 and on the dnncommunity.org website.  In both instances, I was unable to reproduce the issue myself.  

In the browser(s) where some folks can indeed reproduce the issue, I'd suggest trying again in an incognito/private window to rule out the possibility of both cache and browser plugins.

**Comment by X3Technology** [comment]
weird....it does it for me both locally and on .org

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by valadas** [comment]
Ok, i have a working theory that this may happen only at some very specific window sizes can you resize the window to different sizes and refresh the page and see if that behaviour mysteriously disapears and reapers...

**Comment by valadas** [comment]
In the spirit of cleaning up the backlog, I am closing this issue since it cannot be reproduced much and there was no reply since August, if there is any other info that would help make this actionable, please open a new issue.
