### ISSUE TITLE
() Characters that are not illegal are considered illegal characters

### ISSUE THREAD

**Issue by aelibyary** [dnnsoftware/Dnn.AdminExperience#1029]
## Description of the bug
When a user tries to add S.E.O new URL with special characters **(** ,or **)** it'll not work while the error message doesn't really say that these characters are illegal characters as you can see in this [recording](https://www.loom.com/share/2c2049609f314b198000166e877b4247)

## Steps to reproduce
1. Go to any page's settings 
2. SEO Tab 
3. Add New URL > type in a URL like (test)
4. Click Save

## Current result
An error message that illegal characters are in the URL is shown.

## Expected result
An error message should not be shown or fix the error message.

## Screenshots
![image](https://user-images.githubusercontent.com/22526979/61909852-23164180-af01-11e9-8465-14a72a2a38d0.png)

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by mitchelsellers** [comment]
We can update the error message to be more accurate.  As those characters should NOT be allowed

**Comment by valadas** [comment]
I like the proposed PR, since the actual characters are not harcoded but a configuration, it changes the message to not specify the details and provides the suggested url instead. Love it.

**Comment by valadas** [comment]
Merged
