### ISSUE TITLE
Ability to hide persona bar

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.AdminExperience#1039]
## Description 
It is hard to view all content when you use sites that have 100% width.  Personabar hides how it looks and sometimes buttons or links to other parts of the site.
## Steps to reproduce
Install DNN
Login as Host or Administrator
Edit a page with 100% width module or skin menu
## Current result
Cannot view or select anything hidden behind the persona bar
## Expected result
Two options in my mind.

One is the entire website shifts over to where the persona bar edge is so you can see the entire site look and feel along with testing functions such as links and buttons.

The other would be to have a switch or carrot icon/arrow icon that allows you to hide/unhide the persona bar so you can select it.

Another is keep persona bar hidden to the side and only if you hover your mouse over it does it popout and then select with a PIN to pin it open or keep it open if you need it a lot.
## Affected version

* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by mitchelsellers** [comment]
Change have been made to the UI/UX with regards to the Persona Bar.  At this point in time any change to the layout is breaking to others, and there isn't a plan at this stage to adjust the layout-position unless an extensive review as done prior.
