### ISSUE TITLE
Creating new user in Persona Bar asks for Username when using Email as Username

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.AdminExperience#1043]
## Description of bug
Creating a new user in Persona Bar admin UI asks for Username when using Email as Username

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to Settings Users in Persona Bar
2. Click on Add User
3. Scroll down to Username
4. Option to set Username may not be needed using the setting with email address as username

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by sleupold** [comment]
Does this issue still persists in DNN 9.4.0 RC?

**Comment by valadas** [comment]
Yes

**Comment by valadas** [comment]
Closing this one in favor of https://github.com/dnnsoftware/Dnn.Platform/issues/3080 which is the same issue that I just retitled better as this one.
