### ISSUE TITLE
Reinstate "Make page private / Make page public" toggle

### ISSUE THREAD

**Issue by andyduo** [dnnsoftware/Dnn.AdminExperience#1046]
## Description of problem
Since the move to the Persona Bar the 'Make page private / Make page public' toggle was removed. I get clients asking where this is as it was an easy way to do this.

## Description of solution
I suggest adding this back in to the edit page bar next to the Add Module buttons so it is easy to toggle the visibility of a page.

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser

None
* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by mitchelsellers** [comment]
This is a feature that has always caused a number of issues in the past with inadvertent pages being published.  

In situations with multiple roles, this older option used to automatically set "All Users" to view, without any confirmation which can have a very negative impact.  I personally would prefer for the sake of security & management that we NOT add this back in, additionally, this would add clutter to the edit experience that already has a number of icons.

**Comment by valadas** [comment]
I guess it would be a bit of a dangerous 1 click button. Because these was no PR that came in after multiple months of this issue being here and because that could easily be an extension for those who would want that feature, I am closing this issue to clean up the backlog.

**Comment by sleupold** [comment]
I agree with @mitchelsellers
