### ISSUE TITLE
Settings/Delete localization functions is missing in page settings

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.AdminExperience#105]
## Description of bug
Settings/Delete localization functions is missing in page settings

## Steps to reproduce
1. install evoq 9x and login as host; 
2. add a new language and enable content localization in Site Settings; 
3. try to edit any page and switch to Localization tab.

## Current result
only have the view icon, but no gear icon or trash icon.

## Expected result
same functionality with 8x: 
eye icon: click to browse the page; 
gear icon: click to check the page setting of that localized page; 
trash icon: click to delete that localized culture of the page.

## Screenshots
![image](https://user-images.githubusercontent.com/3364448/47341445-96212c00-d6d3-11e8-8dc9-d81d564f977a.png)
![image](https://user-images.githubusercontent.com/3364448/47341450-99b4b300-d6d3-11e8-84dc-f7f33579b456.png)

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

**Comment by tpluscode** [comment]
@zyhfish do you recall why those icons were removed between 8.x and 9.x?

cc @dnnsoftware/tag

**Comment by zyhfish** [comment]
Because in 9x we switched to Persona Bar instead of old admin pages. what i believe this is a missing function but not removed by plan.

**Comment by tpluscode** [comment]
Yes, I know it happened to a number of features. I'm curious in this case however. Just by looking at 8.x and 9.x screenshots I would assume that the UI is pretty much the same, albeit with the 2 icons removed.
