### ISSUE TITLE
When add new site and Assign Current User as Administrator is disabled, form to add admin user is not displayed

### ISSUE THREAD

**Issue by tingung** [dnnsoftware/Dnn.AdminExperience#1054]
## Description of bug
When add new site and Assign Current User as Administrator is disabled, form to add admin user is not displayed. The consequence is user can't create the new site. 

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to Persona Bar > Manage > Sites 
2. Click on Add Site 
3. Enter Site Title, Description, Select Site Template, Site Type as Directory, Set "Assign Current User as Administrator" toggle to off

## Current result
Form to add admin user is not displayed. 

## Expected result
Form to add admin user should displayed.

## Screenshots
If applicable, provide screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/22523590/62031367-ca54ea80-b219-11e9-8a36-db4bfbc567f0.png)

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
Confirmed in 9.4.0 RC also

**Comment by valadas** [comment]
Fixed by #1098
