### ISSUE TITLE
Persona Bar: Users: Role Names overflowing into next line

### ISSUE THREAD

**Issue by noor-zubair** [dnnsoftware/Dnn.AdminExperience#106]
Description of bug
When a Role has a long name such as "Archives content manager Archives content manage 1" it appears to be overlapped in Roles dropdown when assigning role to a User

Steps to reproduce
1. Go to Manage > Roles 
2. Create a couple of roles with a long name such as "Archives content manager Archives content manage 1" and "Archives content manager Archives content manage 2" 
3. Go to Manage > Users 
4. Click on the shield icon for one of the users to add a role to it 
5. Type an A in the search for the roles

Current result
The text jumps the next line causing text to look overlapped. See screenshot
![screenshot-1](https://user-images.githubusercontent.com/38560146/47369843-f75df500-d6fd-11e8-9c50-df126becd3fb.png)

Expected result
It should display the name without overlapping

Affected version
  9.2.1

**Comment by valadas** [comment]
Manually closing since #107 has fixed this.
