### ISSUE TITLE
Search for users not always available

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.AdminExperience#1062]
## Description of bug
Using dnn 9.4.0 RC, you cannot search for:
1. Unauthorized users
2. Deleted Users
3. SuperUsers
4. All Users

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to Users
2. Switch the "Show" dropdown to various types

## Current result
Notice we cannot search for some of theme (see above)

## Expected result
We should ideally be able to search for any type unless this is by design, but I think at least All Users should work

## Additional context
This is a change in behaviour compared the 9.3.2 where we could not search also for some types but the list of non working types was:
1. Unauthorized
2. Deleted
3. SuperUsers

So the major problem I think is All Users that changed from 9.3.2 to 9.4.0 and I think this is kind of important and is a regression. But if this is not by design then fixing it for all would be even better.

## Affected version

* [x] 9.4.0 RC
* [x] 9.3.2

**Comment by sleupold** [comment]
AFAIR the stored procedure supports search for each of the options, however not for other combinations (unauthorized superusers, ...).

**Comment by valadas** [comment]
Hmm, ok, will take a look, would be nice to at least restore the all users one so this one works I am going to take a look at this now.

**Comment by valadas** [comment]
This is now fixed, closing since PR got merged
