### ISSUE TITLE
DataConsentResetTerms.Confirm not localized

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.AdminExperience#1069]
## Description of bug
The confirmation dialog when resetting terms and conditions does not have the proper message and shows DataConsentResetTerms.Confirm instead

## Steps to reproduce
List the steps to reproduce the behavior:
1. Got to Settings -> Site Settings -> Site Behavior ->Privacy
2. Click on the Reset Terms and Conditions button
3. Notice the confirmation message

## Current result
Shows DataConsentResetTerms.Confirm

## Expected result
Should show a human readable message

## Screenshots
![image](https://user-images.githubusercontent.com/6371568/62182335-420f3c00-b324-11e9-84a6-ce9122ebd2d9.png)

## Error log
Nothing logged

## Additional context
Same for the message after accepting that dialog.

## Affected version

* [x] 9.4.0 RC
* [?] 9.3.2

## Affected browser
Used Chrome but probably not browser related

**Comment by donker** [comment]
fixed by https://github.com/dnnsoftware/Dnn.AdminExperience/pull/1180
