### ISSUE TITLE
checksums missing in security analyzer

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.AdminExperience#1076]
Checksums for 9.3.2 and 9.4.0 are currently missing in the security analyzer sums.resources file. This needs to be added before the 9.4.0 release

**Comment by sleupold** [comment]
why do you need checksup for 9..3.2, for installing or upgrading to 9.4.0?
(sorry, I just want to understand)

**Comment by valadas** [comment]
Hmm, good question... I just see them getting added each release, not sure if they are needed at all, maybe we only need the checksums for the current release.

**Comment by valadas** [comment]
Oh, 9.3.2 was evoq only and there was no 9.3.2, so we are just missing 9.4.0 platform, adding this now...

**Comment by valadas** [comment]
Merged
