### ISSUE TITLE
IP address filtering UI is not reflecting the settings correctly

### ISSUE THREAD

**Issue by tingung** [dnnsoftware/Dnn.AdminExperience#1078]
## Description of bug
IP address filtering UI is not reflecting the settings correctly. 

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to Settings -> Security -> Member Accounts -> Member Management 
2. Toggle "On" Enable IP Address Checking And Save 
3. Go to Settings -> Security -> Login Settings ->Login IP Filters 
4. Click "Add New Filters" 
5. Enter 192.168.0.1 into "First IP" 
6. Click "Save" 
7. Edit the filter

## Current result
First IP input text field is blank. Similar behavior for other fields. 

## Expected result
First IP input text field should display the saved value. Other fields should display the saved value. 

## Screenshots
If applicable, provide screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/22523590/62294930-a2c28400-b49e-11e9-992f-81244e558f07.png)
Reproduction video - https://drive.google.com/open?id=140U9IJAe5kN4SIgxRzIy6fe2GBUgoYHE

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
Oh, I just saw this after duplicating the issue, ignore the other one...

This relates to https://github.com/dnnsoftware/Dnn.Platform/issues/2922 which also needs to be fixed for this to work properly.

**Comment by tingung** [comment]
Hi @valadas ,

I will fix 2922 with another PR because it  need to change not only the UI validation but the server side. This issue is not reported by the client but I found  it when I am manually test the IP Filter.

**Comment by valadas** [comment]
Merged
