### ISSUE TITLE
Support to allow all (*) IP Address in IPFilter when creating a new filter

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.AdminExperience#1080]
@tingung commented on [Thu Aug 01 2019](https://github.com/dnnsoftware/Dnn.Platform/issues/2922)

## Description of Problem
The default value for IPFilter is allow all IP Address with value First IP (table IPFilter.IPAddress) set as *. However, user is not allowed to create a new filter with First IP (IPAddress) set as * because both UI validation and server side validation is ensuring the First IP (IPAddress) as valid IP Address.

## Proposed Solution Option 1
Should allow  user to create IPFilter with * as First IP(IPAddress)

## Proposed Solution Option 2 (If Needed, repeat for more)
Another proposed solution to the problem

## Alternatives Researched
This is the changes which blocking the IP Address as * - https://github.com/dnnsoftware/Dnn.Platform/commit/d8815830c5ff467e1a5631e236eb37bd1afec815#diff-3ba5f3f4fffdba1d1cbdaadfd62ce1daR76

## Affected version

* [x] 10.0.0 nightly build
* [x] 9.4.1 nightly build
* [x] 9.4.0 release candidate
* [x] 9.3.2 latest supported release

**Comment by valadas** [comment]
Relates to https://github.com/dnnsoftware/Dnn.Platform/issues/2922 in Platform, 2 PRs will be needed to fix this properly

**Comment by valadas** [comment]
Duplicates #1078

**Comment by tingung** [comment]
Hi @valadas 

Thanks for copy over the issue. I think we can keep this issue. 

If community think this is a valid issue, I will create a bug issue and PR to fix it. It is not duplication of #1078 per se because it need to change not only the UI validation but the server side. This issue is not reported by the client but I found it when I am manually test the IP Filter.

**Comment by valadas** [comment]
Yes, it is a welcome fix, I closed this one because initially I was thinking this will need one issue for the UI too so I created this one, after that I noticed you had already created one in this repo, so mine was not required here since you already had yours. Does this make sense ?
