### ISSUE TITLE
Improve Restart Application and Clear Cache experience

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.AdminExperience#1084]
## Description of problem
Restarting DNN and clearing the cache takes too much time in DNN9 IMO.
I have been doing some templating on a module with heavy caching where I had to restart DNN for every change. That gets really annoying as you need to open the persona bar, click restart, DNN restarts, the persona bar opens again and you have to close the PB.|
Seems like nothing but after 10 times..

## Description of solution
IMO we should add those two links to a more accessible location. I would say here:

![image](https://user-images.githubusercontent.com/8999382/62447919-c3246400-b766-11e9-9914-96a0dfa50258.png)

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1

**Comment by valadas** [comment]
In my opinion those 2 options should be rarely used and as a last resort troubleshooting step, not something that needs prominent visibility. Also on large sites, accidentally clicking this can be trouble. There was also talks about improving the Clear Cache button to be a dropdown or a checkbox list for what to clear and it would need to be in one of the module I believe so we have enough space for that improved UI.

**Comment by Timo-Breumelhof** [comment]
The thing is that with module with heavy caching you need to use those a lot if you are developing a template (example AF). They have been directly accessible in DNN 7 & 8 and AFAIK that hasn't been a real issue in the past and they would only be visible for Host users? (I think one could safely assume a host user will not restart dnn for fun)

**Comment by valadas** [comment]
Modules have their own "Refresh" link in the module actions that should clear the module cache and staying in edit mode is also possible, so I think this covers that use case correctly, cache on the module level can also be disabled in the module settings. And the whole Dnn cache can be disabled in a development site too. I think we have enough ways to solve this without making these controls too easy to accidentally hit, IMO...

**Comment by bdukes** [comment]
I agree with @valadas, those don't need to be easier to access than they already are (via the _Servers_ or _Prompt_ Persona Bar extensions).

**Comment by Timo-Breumelhof** [comment]
Hmm, OK so I guess I'm alone in this. I use it a lot especially locally (after running sql scripts) and the reloading of the PB and not refreshing the page annoys me. Maybe we could at least close the PB and refresh the page after you reset DNN? Does that make sense to you? @valadas @bdukes

**Comment by bdukes** [comment]
Yes, I would be okay with refreshing the main page after clicking _Clear Cache_ 👍

**Comment by sleupold** [comment]
"clear cache" makes sense after working in the database - IMO the best additional place would be the SQL extension (next to run)

**Comment by Timo-Breumelhof** [comment]
@bdukes @valadas not sure how you normally approach this, do I change this issue or do I close it and I create another one?

**Comment by bdukes** [comment]
I think it's probably easier to create a new issue (which mentions this one for context), so the conversation can be more focused. 👍

**Comment by valadas** [comment]
@Timo-Breumelhof yes, this does make sense to me, the main concern here is to not make it too easy to hit accidentally, it has huge consequences on some multi-tenant sites or huge sites.

**Comment by valadas** [comment]
As per discussion, I am closing this issue if favour of more focused ones
