### ISSUE TITLE
UI Issue on Settings > Servers > Server Settings >  SMTP Server Tab

### ISSUE THREAD

**Issue by kkadir** [dnnsoftware/Dnn.AdminExperience#1090]
## Description of bug
When any user who do not have the SMTP Settings permissions on the SMTP Server tab, a.k.a, an Administrator user; navigates to the Settings > Servers > Server Settings >  SMTP Server tab, an extra redundant horizontal-ruler is visible in the right pane of the tab, which is expected to be empty.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Log in as an Administrator user.
2. Go to Persona Bar > Settings > Servers.
3. Click on "Server Settings" Tab.

## Current result
An extra redundant horizontal-ruler is visible in the right pane of the "Server Settings" tab.

## Expected result
The right pane of the "Server Settings" tab should be totally empty without any visual elements for any user who do not have the SMTP Settings permissions.

## Screenshots
![image](https://user-images.githubusercontent.com/8139167/62648419-6a69ec80-b95b-11e9-9b4d-31b0e41a711c.png)

## Error log
N/A

## Additional context
N/A

## Affected version
* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
Confirmed in 9.4.0 RC

**Comment by valadas** [comment]
Merged
