### ISSUE TITLE
Managing version numbers (of code and install packages)

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.AdminExperience#11]
Currently version number have to be managed multiple times across every repository. For [this repository](https://github.com/dnnsoftware/Dnn.AdminExperience.Extensions/search?p=1&q=01.06.00&unscoped_q=01.06.00) alone it's 22 manifest files which have to be changed every time we bump the version (no wonder we bump it ver rarely 🙁). The numbers in the `.dnn` manifests are then taken as the zip installer version. Hence these artifacts, as seen in builds from #539 are still 1.6.0, even though GitVersion wrongly calculated 1.5.1. Just imagine how many there are across all Plaftorm/Evoq codebase.

---

So, with GitVersion we would not have the version number at all. Anywhere! Not in `.dnn`, not in `AssemblyInfo.cs`. Anywhere. That version would only ever be calculated from the git branching. The tool has a lot to offer in terms of configuration. It is being affected mainly by tags and merges with release branches.

Originally created by @tpluscode at https://github.com/dnnsoftware/Dnn.AdminExperience.Extensions/issues/578

**Comment by ohine** [comment]
Comment by @mitchelsellers 

> I personally use AppVeyor to assembly patch based on CI build number, including the actual .NET project & .dnn manifest file for all of our automated DNN builds.
> 
> I'm fully in favor of a consistent process, but due to the install impacts, I believe that we MUST manage this with the .DNN files as that is what drives version when installed to DNN.

**Comment by ohine** [comment]
Comment by @tpluscode 

> I don't think we contradict each other :)
> 
> > I personally use AppVeyor to assembly patch based on CI build number
> 
> Same thing. Just instead of patching with CI build number we'd be patching with what comes from gitversion.
> 
> > I'm fully in favor of a consistent process, but due to the install impacts, [..]
> 
> What "install impacts" do you refer to? If you mean to install tools on developer machines, then no such thing would be required. The CI can be set up to install what it needs and during development that version number is pretty much irrelevant.
> 
> > I believe that we MUST manage this with the .DNN files as that is what drives version when installed to DNN.
> 
> Indeed, those number will be managed by CI setting proper values instead of us having to update hundreds of files whenever we want to release. All you should ever have to do is `git tag v1.7.0` and the CI would create correct packages to be deployed.

**Comment by ohine** [comment]
Comment by @mitchelsellers 

> Ah, in that case, that's slick! Local testing would be my only concern at that point

**Comment by ohine** [comment]
Comment by @tpluscode 

> It would possible to have this run locally with some msbuild tasks. GitVersion actually also comes with such NuGet package.
> 
> On the other hand it is little effort to modify that one .dnn file to create appropriately versioned package for manual testing. What do you think?

**Comment by valadas** [comment]
@ohine I know something was done for versions, is this issue still relevant or needs closing?

**Comment by valadas** [comment]
Closing this due the last message being in april, I am assuming this is now done the way it was discusses. Feel free to reopen if there is still something to do with this.
