### ISSUE TITLE
Persona Bar > Manage > Pages > Expand All Fails After Adding Multiple Pages

### ISSUE THREAD

**Issue by kkadir** [dnnsoftware/Dnn.AdminExperience#1112]
## Description of bug
The "Expand All" link stops functioning after adding page(s) through the Add Multiple Pages flow.

## Steps to reproduce
1. Log in as Super/Host user to Platform. 
2. Navigate to Persona Bar > Manage > Pages. 
3. Click on the Add Multiple Pages button. 
4. Input a new page name. 
5. Click the "Add New Page(s)" button. 
6. Observe that the new page(s) is/are added to the "Pages List" tree-view. 
7. Click on the "Expand All" link on top of the "Pages List" tree-view.

## Current result
1. All items in the "Pages List" tree-view are in the collapsed state 
2. Clicking on the "Expand All" link; 
   1. Does not change the link as "Collapse All" 
   2. Does not expand all child items in the "Pages List" tree-view

## Expected result
1. All items in the "Pages List" tree-view are in the collapsed state 
2. Clicking on the "Expand All" link should; 
   1. Change the link as "Collapse All" 
   2. Expand all child items in the "Pages List" tree-view

## Screenshots
N/A

## Error log
N/A

## Additional context
N/A

## Affected version
* [x] 9.4.0 RC

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
Assigning this to the 10.0.0 milestone as per the PR, if things change we can update.

**Comment by valadas** [comment]
Merged
