### ISSUE TITLE
RFC:  Workflow Management UI (Not Implemented)

### ISSUE THREAD

**Issue by mikesmeltzer** [dnnsoftware/Dnn.AdminExperience#112]
## Description of problem
Currently, there is a Workflow API that has been in the platform since v7.4 but it does not have an API to  manage (create, read, update and delete) workflows.

Given that this API has been around for a few years, there could be people using it in there solutions today as the workflows can be added from either the API or directly into the database.

## Description of solution
1. From the Persona Bar, we should have a Persona Bar Extension that allows the CRUD of workflows to occur.

2. Prompt commands could be implemented to mange the workflows (probably should be even if the UI is created to keep feature parity)

3. The Core HTML Module uses it's own workflow implementation.  This module should be migrated to using the core workflow implementation and provided as an example to other module developers on how to use this functionality.

## Description of alternatives considered
Before investing in this work we should determine:

- Do we want to have workflows at a core level going forward?
- Is the current implementation of workflow satisfactory? If not, why 

## Additional context
I created a sample module that implements content workflow at:  
https://github.com/mikesmeltzer/DnnWorkflowExampleModule

## Affected version

* [x] 7.4 +

## Affected browser

N/A

**Comment by ohine** [comment]
@mikesmeltzer can you create this in the main platform repo and close this issue? We want to keep all RFC's in one place to help with being able to review everything on one screen.

**Comment by mikesmeltzer** [comment]
Closing this issue and moving it to the other repo.
