### ISSUE TITLE
Scheduler: web server dropdown is failing due to javascript error

### ISSUE THREAD

**Issue by mikebigun** [dnnsoftware/Dnn.AdminExperience#1128]
## Description of bug
On a scheduler, web server dropdown failing due to javascript error.

## Steps to reproduce

1. Make sure multiple web servers are added
2. Login as admin
3. Go to `Persona Bar` -> `Settings`
4. Go to `Scheduler` - > `Scheduler tab`
5. Change web server in dropdown

## Current result
List of schedulers is not selecting according to selected web server. There is a javascript error saying that `selectedIndex` is undefined.

## Expected result
Dropdown should work properly. List of schedulers should be selected according to web server. No js error should appear. 

## Screenshots

![image](https://user-images.githubusercontent.com/22524011/63753331-65d18d80-c8a2-11e9-9281-af88e686ccac.png)

## Error log

Uncaught TypeError: Cannot read property 'selectedIndex' of undefined 
    at t.value (<anonymous>:1:88552) 
    at Dropdown.value (export-bundle.js?cdv=52:1) 
    at Object.<anonymous> (export-bundle.js?cdv=52:90) 
    at _ (export-bundle.js?cdv=52:90) 
    at export-bundle.js?cdv=52:90 
    at E (export-bundle.js?cdv=52:90) 
    at O (export-bundle.js?cdv=52:90) 
    at k (export-bundle.js?cdv=52:90) 
    at L (export-bundle.js?cdv=52:90) 
    at wn (export-bundle.js?cdv=52:90) 

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by valadas** [comment]
Merged
