### ISSUE TITLE
Template Exports fails

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.AdminExperience#1133]
# Description of bug
Although not implemented in the UI, Template export exists in SitesController of the Sites project. Calling this using WebAPI exposed one issue: if tabs were stacked hierarchically the exported template would be incomplete.

## Steps to reproduce
1. Create a site where you move an old tab underneath a newer tab
2. Create your own Javascript front end and call into api/Sites/ExportPortalTemplate
3. Check template

## Current result
Incomplete template

## Expected result
Complete template

## Affected version
* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x ] 9.1
* [x ] 9.0

**Comment by valadas** [comment]
Merged
