### ISSUE TITLE
Unable to set membership settings "Use Email Address as Username" ON

### ISSUE THREAD

**Issue by aelibyary** [dnnsoftware/Dnn.AdminExperience#1135]
## Description of bug
For some reason enabling "Use Email Address as Username" is returning an error message "Could not update settings"
See the
[recording](https://drive.google.com/file/d/1L9ob3XsCVue3zvje1wv2DBmbXNo2wmJO/view)

## Steps to reproduce
1. Navigate to Settings > Security page 
2. Click on Member Accounts tab 
3. Click on Registration Settings tab and select "Use Email Address as Username" toggle button on 
4. Click on Save button

## Current result
It is showing error message "Could not update settings"

## Expected result
It should save the Registration settings and return a success message.

## Screenshots
![screenshot-1](https://user-images.githubusercontent.com/22526979/64008683-1b504b00-cb06-11e9-9d5b-98ff71bc70a1.png)

## Additional context
This issue is not always reproducible but it happens mainly after adding couple of users.

## Affected version
* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
Merged
