### ISSUE TITLE
Stack traces in Admin Logs missing style

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.AdminExperience#1140]
## Description of bug
The stack traces for exceptions in Admin Logs are displayed without line breaks, despite being rendered in a `<pre>` tag.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Install the example module from https://github.com/dnnsoftware/Dnn.Platform/issues/2972
2. Add it to a page
3. View the exception it throws in Admin Logs

## Current result
Displayed without any line breaks
![Inner Stack Trace without line breaks](https://user-images.githubusercontent.com/59507/64184510-29b5a400-ce31-11e9-8dab-712a9ef34588.png)

## Expected result
Displayed with line breaks
![Inner Stack Trace with line breaks](https://user-images.githubusercontent.com/59507/64184564-40f49180-ce31-11e9-8241-2d77fce9bd2c.png)

## Affected version

* [x] 9.4.0 RC 1
* [x] 9.3.2

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
Merged
