### ISSUE TITLE
PersonaBar closing action does not reset <body> overflow value properly

### ISSUE THREAD

**Issue by tingung** [dnnsoftware/Dnn.AdminExperience#1150]
## Description of bug
When the PersonaBar is open the CSS style "overflow: hidden" is applied on the tag. After closing the PersonBar the tag gets the styling "overflow: auto;" which is a problem as "auto" is not the default value for overflow (it's "visible"). In other words: After opening and closing the PB, the body tag isn't in the same state as it was before.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Login as Host and observe the PersonaBar
2. Inspect the body tag and observe the style doesn't contain overflow attribute
3. Click on PersonaBar and observe the PersonaBar is opened. 
4. Inspect the body tag and observe the style contain overflow attribute.
5. Click on PersonaBar and observe the PersonaBar is closed.
6. Inspect the body tag and observe the style contain overflow attribute

## Current result
Body tag's style contains overflow attribute after closing PersonaBar

## Expected result
Body tag's style should not contains overflow attribute after closing PersonaBar

## Screenshots
https://drive.google.com/file/d/153s6Em2jjb5DWmn1X3jzWRO4y5aKhVhA/view?usp=sharing

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
This is a duplicated of #1030, please add anything to it if there is anything here not covered in the existing issues, thanks.
