### ISSUE TITLE
Sites Module in Persona Bar not populating the correct site details

### ISSUE THREAD

**Issue by tingung** [dnnsoftware/Dnn.AdminExperience#1152]
## Description of bug
Sites Module in Persona Bar not populating the correct site details

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to Persona Bar -> Manage Sites 
2. Create at least two new sites.
3. Click the "setting" icon of the site. 
4. Repeat step no 3 and observe the site information are not populated correctly

## Current result
Site information populated is not the selected site. 

## Expected result
Site information populated correctly for the selected site. 

## Screenshots
https://www.loom.com/share/86934c6b33d14b30b37df17b05a05b80

## Error log
Paste the error log that is related to this issue.

## Additional context
Looks like the site navigation is working correctly except the "view" icon is not working as expected. 
It is also point to the current site. 

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
Merged
