### ISSUE TITLE
SQL console columns are not displayed on when many columns in result

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Dnn.AdminExperience#1160]
## Description of bug
Not all columns are displayed if you execute a query with more than a few fields

## Steps to reproduce
List the steps to reproduce the behavior:
1. Log In as Host
2. Select SQL Console
3. Enter and execute query: `select * from tabs`

## Current result
Not all fields are displayed

## Expected result
All fields/columns visible

## Screenshots
-

## Error log
-

## Additional context
-

## Affected version

* [x] 9.4.0
* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
I am not able to reproduce this, I get a scrollbar to got left and right and it looks like I see everything... Do you have more insight on this ?

**Comment by EPTamminga** [comment]
Sorry, I completely overlooked the (non-standard and small) scrollbar at the bottom of the grid.
