### ISSUE TITLE
Add a message after localization update finishes

### ISSUE THREAD

**Issue by daguiler** [dnnsoftware/Dnn.AdminExperience#1171]
## Description of bug
After https://github.com/dnnsoftware/Dnn.AdminExperience/issues/1161 we see a warning message before localization update begins, but after the user clicks `Continue`, no further feedback is provided.

## Steps to reproduce
1. Enable a secondary language
2. Create a page under the main language (en-us)
3. Open the page settings > Localization and add missing languages
4. Click all available module checkboxes on the added language
5. Click on `Update Localization`. A warning is displayed.
6. Click `Continue`

## Current result
After the warning is dismissed a brief progress bar is visible at the top and then nothing else seems to happen.

## Expected result
User should get feedback of when localization process has finished.

## Affected version

* [x] 9.4.1

**Comment by valadas** [comment]
Merged
