### ISSUE TITLE
UI issue for pages Expand All/Collapse All links

### ISSUE THREAD

**Issue by mikebigun** [dnnsoftware/Dnn.AdminExperience#1183]
## Description of bug
Expand All/Collapse All link in persona bar pages tree section is displayed as selected and highlighted by default. Regression found in the following PR https://github.com/dnnsoftware/Dnn.AdminExperience/pull/229. Instead of just making Expand/Collapse link clickable when child nodes loaded, the style of link was also changed in a way to make it highlighted regardless of state.  

## Steps to reproduce

1. Install DNN Platform from scratch
1. Login as super user
2. Go to Persona Bar -> Pages

## Current result
Pages screen is displayed. Expand All link in pages tree section is displayed as selected and highlighted in blue color.

## Expected result
Expand All should not be highlighted by default on Pages screen. Link should be highlighted depending on whether it is clicked or not. 

## Screenshots

![image](https://user-images.githubusercontent.com/22524011/65950261-3d066000-e42d-11e9-81c7-47737bda43c1.png)

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by valadas** [comment]
After discussing this, it would violate accessibility requirements due to lack of color contrast, sorry, closing this pr and issue for that reason.
