### ISSUE TITLE
Security Analyzer : CheckDiskAccess always a warning

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.AdminExperience#131]
Moved from https://github.com/DNNCommunity/DNN.SecurityAnalyzer/issues/24

Originally opened by @mkosse

I have changed the settings for the security to one single user that has only access to one folder on my disk. (I checked the permissions) however the CheckDiskAccess keeps giving warnings on this point.

Am i missing something? because it looks like a bug..

---

@Timo-Breumelhof original comment:
I think the analyser is correct. You should remove access for the User group to other folders as the "App pool user" is also a member of the Users group.
(you should change anonymous authentication to apppool user though or the result will be a site without stylesheets. :-)

---

@ashishpd  commented:
Please read this article for more details. Essentially, one needs to remove Users group from the folders hosting the website(s), and explicitly add the App Pool user to the folder. https://stackoverflow.com/questions/5437723/iis-apppoolidentity-and-file-system-write-access-permissions

**Comment by valadas** [comment]
@ashishpd and @Timo-Breumelhof

Is the security analyzer reporting this wrong or what is the fix here? 
When setup as explained in the documentation at https://www.dnnsoftware.com/docs/administrators/setup/set-up-dnn-folder.html the analyzer reports this problem but running an audit with the application pool user shows that it cannot access the mentioned folders, so it looks like the analyzer is wrong.

When removing the users group from the containing folder, the css breaks and you need to do what @Timo-Breumelhof commented to restore it. But even with that setup, the security analyzer still repports that issue.

So I am not sure here if we need to fix the analyzer or better document how the permissions should be setup in the documentation or a combination of these two things.

**Comment by Timo-Breumelhof** [comment]
It's a while ago, but I wrote my own code to try and access the folders listed as accessible and the SA was right. But there's a difference between Win2012 and 2016 I think.

**Comment by Timo-Breumelhof** [comment]
So IMO the security analyzer is right.

**Comment by valadas** [comment]
So we need to better document how to set the permissions right then. @Timo-Breumelhof do you know how it should be set correctly?

**Comment by Timo-Breumelhof** [comment]
I prepared blog post, which I never published TBH but that was on Win2012. I'll see if I can find it ;-)

**Comment by david-poindexter** [comment]
Very interested in this one.

**Comment by Timo-Breumelhof** [comment]
Found it, shall I post it in the MVP forum first to discuss? I would like some feedback before turning this into a blog post..

**Comment by valadas** [comment]
@Timo-Breumelhof Sure thing, good idea. Please put a link here to that post so we get a reference back to that discussion. Thanks.

**Comment by Timo-Breumelhof** [comment]
Not public as it should not be indexed:
https://www.dnnsoftware.com/forums/forumid/228/threadid/543801/scope/posts

**Comment by valadas** [comment]
I have tried the steps in the forum post and still get the same, I am tagging this as an rfc until we know what needs to be done here...

**Comment by Timo-Breumelhof** [comment]
What kind of access do you see? I noticed a big difference between a desktop en and a server version of windows BTW.

**Comment by valadas** [comment]
It looks like this is an expected behaviour with ApplicationPoolIdentity on full trust mode. For that reason I am closing this issue, if further discussion is needed, please comment.
