### ISSUE TITLE
Build Nupkgs on CI and publish to MyGet feed

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.AdminExperience#133]
## Summary

Evoq builds sometimes require to reference the latest prerelease changes of Admin Experience libraries.

We should be creating the nuget packages at every successful build and pushing them to the public feed: https://www.myget.org/feed/Packages/dnn-software-public

Once a release is complete, the latest version should then be published to nuget.org

I see that currently VSTS does not even build those packages, or at least does not store them as build artifacts

**Comment by ohine** [comment]
Any update on the ETA for this? As we need this for the v9.3.0 release.

**Comment by valadas** [comment]
What is the status on this issue, is it good to close now ?

**Comment by valadas** [comment]
I am closing this issue since there was no replies for quite some time
