### ISSUE TITLE
Persona Bar: Upgrade React and Use new React Component Library

### ISSUE THREAD

**Issue by mtrutledge** [dnnsoftware/Dnn.AdminExperience#142]
## Description of problem
Is your feature request related to a problem? Provide a clear and concise description of the problem.
The Dnn.React.Common project has changed its structure from 50 individual components to a single component package. We need to update the Dnn.AdminExperience project to use the new component package and a new React version. 

Here is a link to the related issue on the Dnn.React.Common project: [https://github.com/dnnsoftware/Dnn.React.Common/issues/155](https://github.com/dnnsoftware/Dnn.React.Common/issues/155)

## Description of solution
Upgrade package.json files to use React 16.4.2 and @dnnsoftware/dnn-react-common package ^2.0.0

## Affected version
There are no affected versions. This is a upgrade for future versions.

**Comment by mtrutledge** [comment]
I am currently working on this

**Comment by valadas** [comment]
@mtrutledge I think this can be closed now, if not please reopen.

**Comment by mtrutledge** [comment]
Yep should be good to close
