### ISSUE TITLE
Logout and page

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.AdminExperience#15]
When clicking on logout (personabar), nothing happens (there is a web api request made).
I think its better to refresh the page after logout (response of 200).

Originally created by @kurtwilbies at https://github.com/dnnsoftware/Dnn.AdminExperience.Extensions/issues/191

**Comment by valadas** [comment]
I cannot reproduce this issue. This was originally reported one and half years ago, so I guess it was fixed at some point and this issue was just not closed.

@dnnsoftware/approvers can you please close. @kurtwilbies if you can reproduce on the latest version, please open a new issue.

**Comment by valadas** [comment]
Ha I cant tag all approvers... @ohine I think this can be closed
