### ISSUE TITLE
Content Localization: shared module un-published after changes

### ISSUE THREAD

**Issue by mikebigun** [dnnsoftware/Dnn.AdminExperience#151]
## Description of bug
When multiple languages installed and all pages are translated and published, shared module is disappearing from all places when changing `IsLocalized` module property on a particular page settings.

## Steps to reproduce
1. Add a module to a page, and go to `Settings > Add Module` to all pages. Save. 
2. Go to `Settings > Site Settings > Languages`, and add a second language, then enable content localization and localize all of the default pages. 
3. Visit the page with another language, and change the content of the module that is set to be added to every page. 
4. Make sure the content has changed on all of the pages of that language. 
5. Go to the page settings for one of the other pages in that language. 
6. Under Localization click on the chain next to the module added to every page. This will make it a reference instead of a copy. Then hit Update Localization. 
7. Click the chain again to make it a copy, hit update localization
8. Refresh the page and check other pages of this language

See reproduction demo: [localization.mp4](https://drive.google.com/file/d/1eehFMKI1rVPEz8cMgBaxjVFfw8AThgZW/view?usp=sharing)

## Current result
The module added to all pages is no longer visible. If you go into edit mode it is still present on all pages, but not visible.

## Expected result
This case should be handled better. It should either just break the module on the current page, or warn the user if its a module shared everywhere.

## Affected version
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by valadas** [comment]
I also had reports of similar issues with modules localization but could not get clear steps to reproduce. Thanks for documenting this properly!
