### ISSUE TITLE
Send An email to new user is not working

### ISSUE THREAD

**Issue by Icidis** [dnnsoftware/Dnn.AdminExperience#173]
## Description of bug
When creating a new user account as a SuperUser/Admin and checking the "Send An Email To New User." checkbox, no email is sent to the email I specify.

Once the user is created, sending password reset links, etc. work fine. Emails are sent and received correctly so it appears the SMTP settings are correct.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to 'Manage Users'
2. Click on 'Add User'
3. Fill in user details
4. Check the "Send An Email To New User" checkbox
5. Click "Save"

## Current result
The user is created successfully but no email is sent to the user.

## Expected result
User gets created and registration email is sent to the users' email address.

## Additional context

This is related to this issue logged on the Dnn.Platform repo.

[https://github.com/dnnsoftware/Dnn.Platform/issues/2424](https://github.com/dnnsoftware/Dnn.Platform/issues/2424)

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2

## Affected browser

* [x] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
The issue should have been closed by #174 , closing it manually
