### ISSUE TITLE
Dnn.PersonaBar.Users project cleanup post initial GreenKeeper Merges

### ISSUE THREAD

**Issue by mtrutledge** [dnnsoftware/Dnn.AdminExperience#176]
## Description of bug
Need to upgrade the Users persona bar component to the latest react, react common, babel, and webpack.

**Comment by mtrutledge** [comment]
I am working on this one

**Comment by mtrutledge** [comment]
@mean2me did PR #178 for this issue

**Comment by valadas** [comment]
Closing this manually since PR got merged.
