### ISSUE TITLE
Extension Settings: Control Selection

### ISSUE THREAD

**Issue by SCullman** [dnnsoftware/Dnn.AdminExperience#186]
## Description of bug
It is impossible to select the right control in the UI: 
![image](https://user-images.githubusercontent.com/5693190/49338027-17e26e80-f61d-11e8-91eb-ede735feffcc.png)
I always need to open the developer tools to verify my selection 

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to PersonaBar/Settings/extensions/ExtensionSettings
2. Edit/add a ModuleDefinition
3. Try to select the right control

## Affected version

* [x] 9.2.2

**Comment by SCullman** [comment]
I also volunteer to fix that. Is there a schedule by when the PR has to be done to get into the next release?

**Comment by ohine** [comment]
Thanks for logging the issue and volunteering to fix it @SCullman!

The code-freeze date for v9.3.0 is currently 12/17. We try and keep the [roadmap](https://www.dnnsoftware.com/community/learn/roadmap) updated if the date gets pushed. I usually update during the TAG planning meeting if we need to adjust the date.

If you have any questions or run into any problems. Feel free to ping me!

**Comment by SCullman** [comment]
@ohine, I need some [help](https://github.com/dnnsoftware/Dnn.AdminExperience/pull/200#issuecomment-444270433). I fixed the code - but I can't get it bundled to verify my changes.
