### ISSUE TITLE
Upgrade RequireJS to latest version

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.AdminExperience#2]
## Description 

Upgrade RequireJS to latest version, currently we have 2 places of requirejs referenced:

1. StructuredContentVisualizer module - version 2.3.3
2. PersonaBar - version 2.1.11

Latest version: http://requirejs.org/docs/download.html version 2.3.5
need upgrade both places to 2.3.5 and make sure nothing is broken.

Originally created by @tpluscode at https://github.com/dnnsoftware/Dnn.AdminExperience.Library/issues/157

**Comment by ohine** [comment]
Comment by @tpluscode 
> @zyhfish, would you explain why it's important for Persona Bar to upgrade? Is there any conflict between the version in Structured Content and Platform? Are there any benefits from upgrading?

**Comment by ashishpd** [comment]
An Evoq customer has requested the update to RequireJS. They want to take advantage of the new capabilities in RequireJS. When can this be merged?

**Comment by mitchelsellers** [comment]
This issue will be addressed as part of the 9.3.0 release, along with many other version upgrades for third-party references.  Given that the update requires a minor version upgrade of a third-party library we are including it in a minor version upgrade of DNN.

Milestone updated on the PR for this

**Comment by ashishpd** [comment]
Now that 9.2.2 is out, @ohine, @mitchelsellers are we able to merge this for 9.3?

**Comment by ohine** [comment]
Closing as this was already handled with https://github.com/dnnsoftware/Dnn.AdminExperience/commit/3e7c115099303174d32f903851d67c2130667e18

**Comment by ohine** [comment]
Well, at least it was handled in platform. @ashishpd you might want to just confirm that StructuredContentVisualizer was updated in Evoq as well.
