### ISSUE TITLE
Accessibility of the PersonaBar is pretty bad

### ISSUE THREAD

**Issue by OllyHodgson** [dnnsoftware/Dnn.AdminExperience#21]
## Description 

A recent post by Katherine Moss to the DNN Connect facebook group has highlighted the accessibility of the Persona Bar is practically non-existent.

A quick look reveals:

- Keyboard navigation (i.e. tabbing through the links on the page) doesn't ever highlight any of the icons in the Personabar or Edit Bar. This is likely to be because the functionality is directly bound to `<li>` elements - not `<a>` or `<button>` elements which are focusable "for free".
- There are no `role` or `aria` attributes anywhere in the Persona Bar. Perhaps [this W3C toolbar example](https://www.w3.org/TR/wai-aria-practices/examples/toolbar/toolbar.html) would be a good role model for DNN?
- The SVG icons have no alt or title text (I'm unsure of the best approach here). 

I'm no expert, but even I can see that for a non-sighted user, the DNN 9 admin interface must be nigh on impossible to use.

## Steps to reproduce

Open Firefox dev tools. Enable the Accessibility panel. Browse through the Persona Bar. Note that there is almost no useful information there.

Install the [Landmarks extension for Firefox/Chrome/Opera](http://matatk.agrip.org.uk/landmarks/). Load a DNN page. Note that the PersonaBar and Edit Bar do not appear.

Try the PersonaBar with other accessibility testing tools. The [WAVE extension](https://wave.webaim.org/extension/) doesn't seem to notice it at all, but that might be a limitation of the extension.

## Current result

Users of assistive technology really struggle to use DNN's admin interface.

## Expected result

Users of assistive technology can use DNN's admin interface.

## Affected version

* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

**Comment by Cambridgeport90** [comment]
You have everything absolutely correct. This was an issue, though, in other ways in versions 8.0 and below, as well, though at least it was useable with custom extensions. In regards to the current version, I need to know what I can do to speed this up, for one, and for two, to assist in making accessibility part of the DNN development process for all, not just the front end. I wholeheartedly commend all the testing that's gone into making the front end accessible. I'm willing to test each new release, but I think that in the short term, accessibility on the backend needs to be brought to pretty much a priority one.

**Comment by EPTamminga** [comment]
One improvement is to make the PB stay fixed on the page and not slide in. 

A suggestion (by Sacha Trauwen) for this was to add the line 

`body {margin-left:80px !important;}` in the `personaBarContainer.css` 

to avoid flickering

**Comment by Cambridgeport90** [comment]
Let me know when this happens, and what to look for in future testing. I want to help you guys out wherever I can.

**Comment by EPTamminga** [comment]
If you have a DNN9.x test site, you can add this line to the .css file and evaluate if you think if that is a UI improvement (for me, it is).

**Comment by Cambridgeport90** [comment]
I can’t see the text of the line to add. If you took a screenshot, please don’t. Not helpful to blind folks.

**Comment by OllyHodgson** [comment]
@EPTamminga That CSS change won't make a lot of difference to a blind user :-) The issue is a bit more fundamental - the personabar is basically invisible to screen reader software!

**Comment by EPTamminga** [comment]
No, I did not make a screenshot, I think that the GitHub issue formatting changed my text. It specifies that a .css line can be added to a specific .css file of the persona bar (and these are very technical words for a screen reader I assume)

A new attempt in plain text:

Add the line:

body { margin-left: 80px !important; } 

in the :

personaBarContainer.css

to avoid flickering of the persona bar

**Comment by EPTamminga** [comment]
@OllyHodgson Yes, I am aware that the persona bar is invisible to a screen reader. 
That was one of the issues discussed in the DNN technology advisory group yesterday as a serious shortcoming of the current version of the persona bar. 
It must be addressed in an upcoming release.

**Comment by Cambridgeport90** [comment]
It might be about flickering, though it’s more fundamental than that. Take a look at:
https://docs.microsoft.com/en-us/dotnet/framework/ui-automation/

**Comment by EPTamminga** [comment]
@Cambridgeport90 
I know, I know. 
It is not me who created the persona bar, in fact, I am not a fan of the current way it works. But, if people and are willing to spend some effort on generating ideas, coding and testing, it can become a better usable component in DNN. 
The foundation is there, we have to refurbish the building.

**Comment by Cambridgeport90** [comment]
Indeed. That’s why every test I want to be a part of. I’m probably going to set up a web server as well with auto-deploy from the latest nightly builds in addition to the prod one I have, and we’ll go from there. Only siteI have up right now is our prod site.

**Comment by mitchelsellers** [comment]
@Cambridgeport90 Just confirming for you that right now the screen reader does not see any of the PersonaBar components at all, correct?  Including the version information that is at the start of the PB. (I know a hard question when unable to see the screen)

**Comment by Cambridgeport90** [comment]
You are very right. Worse, it recognizes it differently per screen reader (NVDA will recognize the elements on the page, but will not read their labels, referring to them as “clickable”, and  JAWS will not recognize the frame at all), but yes, this is the case. Then, when you get into one of the options in the frame, you have to do this weird swap thing where you have to swap NVDA for JAWS to get it to work properly, and even then, it takes a lot of playing around with cursor routing (a way for screen readers to (hopefully, though it’s a total pain), handle mislabeled elements), in order for the actions button to do something, and then I see  ton of “add module” buttons on the page. Not sure why that exists like eighty times, but it seems to. When adding a module, again, whereas it should display as a nice, scrollable combobox (Alt+down arrow to open it, up/down to scroll), it doesn’t and you just have to hope to God that the module you want actually is the one you get.

**Comment by OllyHodgson** [comment]
I've never really looked at the PersonaBar code before, but I'm looking at adding `aria-label` and `aria-haspopup` attributes, and making the top-level items keyboard navigable. If I can make it work, it'll be a good start.

I guess I'll need to do the CLA thing, at some point? I'll have a read of the contributing documentation.

**Comment by Cambridgeport90** [comment]
That would be great. How they are not keyboard navigable in the first place, I would like to know; after all, default controls are, unless there is a custom control, here? That’s what it sounds like, though with my development skills incredibly weak at the moment, I could be missing something.

**Comment by OllyHodgson** [comment]
> How they are not keyboard navigable in the first place, I would like to know; after all, default controls are, unless there is a custom control, here? That’s what it sounds like, though with my development skills incredibly weak at the moment, I could be missing something.

It's because the click/hover events were bound directly to the `<li>` elements instead of something more sensible like an `<a>` or `<button>` which can be keyboard focused for free. #sigh

**Comment by Cambridgeport90** [comment]
Cool. Is that in the backend C# code behind, or is that a HTML/CSS fix? I’m thinking the former, but at least it is hopefully easy to fix. And remind me what <li is? I thought that meant list?

**Comment by OllyHodgson** [comment]
You're right, `<li>` is a list item. The personabar is all lists.

As for the code, it's all HTML, CSS and JS. I've started with `index.html` and `scripts/main.js` in https://github.com/dnnsoftware/Dnn.AdminExperience/tree/development/Library/Dnn.PersonaBar.UI/admin/personaBar

**Comment by Cambridgeport90** [comment]
Keep us updated! And thanks again!

**Comment by OllyHodgson** [comment]
OK, after my first look, I think this is going to be better handled as a series of smaller issues referenced from this one. Otherwise we'll have one almighty pull request from someone who has never worked on the PersonaBar (or any other part of the platform) before.

In other words, I'll break this down into smaller chunks.

**Comment by Cambridgeport90** [comment]
that definitely ought to work. I look forward to seeing what happens here. This is going to be interesting.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by valadas** [comment]
I am closing this issue in favor of the multiple smaller chunk ones which will be easier to manage, if this is a mistake, please comment and I will be happy to reopen.
