### ISSUE TITLE
Seo priority not saved right

### ISSUE THREAD

**Issue by sachatrauwaen** [dnnsoftware/Dnn.AdminExperience#223]
## Description of bug
In Admin Settings, Seo, Sitemap settings, sitemap providers is the Override Priority not saved correctelly.
Dnn sitemap generation wait for a override value multiplied by 100 but the saved value is the real value (with decimal separator).

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to 'Admin Settings, Seo, Sitemap settings, sitemap providers 
2. Save a value of 0.5 for the coreSitemapProvider
3. look in the db table portalsettings , record with coreSitemapProviderValue as SettingsName
4. the saved value is 0.5 in place of 50

## Current result
The priority field for all pages in sitemap.aspx equals 0

`<url>
<loc>https://www.vcomm.be/fr-fr/</loc>
<lastmod>2018-12-03</lastmod>
<changefreq>daily</changefreq>
<priority>0.0</priority>
</url>`

## Expected result
The priority field for all pages in sitemap.aspx equals 0.5
`<url>
<loc>https://www.vcomm.be/fr-fr/</loc>
<lastmod>2018-12-03</lastmod>
<changefreq>daily</changefreq>
<priority>0.5</priority>
</url>`

## Affected version

* [x] 9.2.2

**Comment by valadas** [comment]
I can reproduce and I am working on it now.

**Comment by valadas** [comment]
PR Merged
