### ISSUE TITLE
Script bundles should be deleted and ignored

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.AdminExperience#245]
If pull requests are not merged in order (often happens), there is always a merge conflict with the minified bundle script. This file gets generated by the build so it is not needed in the commits, it should be deleted from the repository and added to the gitignore file to simplify merging pull requests.

**Comment by ohine** [comment]
Fixed in #255

**Comment by valadas** [comment]
That got done in #255 Bye Bye Bundles,
