### ISSUE TITLE
Cannot edit a user

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.AdminExperience#264]
## Description of bug
Clicking on any user field collapses the collapsible section so we cannot edit fields.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Create a test user and save it
2. Try to change any field

## Current result
The collapsible section collapses

## Expected result
Should not collapse and we should be able to do edits

## Error log
No errors get logged

## Additional context
Also happens on the ... menu when clicking change password

## Affected version
9.3.0.103

**Comment by kurtwilbies** [comment]
Whats the reason behind this amount of bugs?

**Comment by valadas** [comment]
Not sure yet, just went though all the modules and tried all the features and logged issues I found. Did not troubleshoot at all yet since I just wanted to log all issues that needed attention for 9.3.0. Feel free to pickup any issue so specifically assigned to someone, all pull requests or troubleshooting details is welcome

**Comment by valadas** [comment]
#261 probably solved this, cannot reproduce with latest code.
