### ISSUE TITLE
Configuration Manager files are offset compared to selection

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.AdminExperience#272]
## Description of bug
When selecting a file in the dropdown of the configuration editor, the next file shows instead of the selected one.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Select DotnetNuke.Log4Net.config
2. Notice the Analytics.config file shows
4. Select the Analytics.config file
5. Notice the SiteUrls.config file shows
6. Rinse and repeat for each

## Error log
No errors logged

## Additional context
Probably in incorrect usage of some index 0 vs 1 start

## Affected version

* [9.3.0.130]
* [ ] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by skamphuis** [comment]
I'm looking into this one. (just to prevent double work)
