### ISSUE TITLE
Refactor GetUser Command Unit Test to Inherit from CommandTest

### ISSUE THREAD

**Issue by Mohtshum** [dnnsoftware/Dnn.AdminExperience#28]
## Description of bug
GetUserUnitTests should inherit from CommandTest Generic class to achieve DRY

## Steps to reproduce
Go to the implementation of  Extensions\Manage\Dnn.PersonaBar.Users.Tests\GetUserUnitTests.cs

## Current result
It does'nt inherit from CommandTest

## Expected result
It should be inheriting from CommandTest 

## Affected version

* [x] 9.2.1
* [x] 9.2

**Comment by valadas** [comment]
This is merged and the issue should have auto-closed.
