### ISSUE TITLE
DNN Products > Persona Bar > Settings > Prompt > get-portal displays blank screen & console errors

### ISSUE THREAD

**Issue by Mhtshum** [dnnsoftware/Dnn.AdminExperience#285]
## Description of bug
get-portal and get-site are giving blank screen and errors in console of browser

## Steps to reproduce
1. Log in As Super User in Evoq Engage 
2. Go to Persona Bar > Settings > Prompt 
3. Type command get-portal/get-site 

## Current result
Application executes the command and blank screen is displayed. Console shown below error:
export-bundle.js?cdv=130:90 TypeError: Cannot read property 'toString' of null

## Expected result
Portal/Site information should be displayed. 

## Error log
export-bundle.js?cdv=130:90 TypeError: Cannot read property 'toString' of null

## Affected version
* [x] 9.3.0

**Comment by valadas** [comment]
Very probably caused by https://github.com/dnnsoftware/Dnn.Platform/pull/2522

@Mhtshum did you try this on a build after 2018-12-28 or before that ?

**Comment by Mhtshum** [comment]
@valadas It was reported on 2018-12-31. But it doesn't relate with that, may be because of upgrade undefine check not working properly
