### ISSUE TITLE
Branch cleanup

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.AdminExperience#3]
@dnnsoftware/tag 

Here's what I propose to clean up branches and branch strategy here:

1. tag the `HEAD` of each release branch with a matching tag
1. merge release branches into `development` starting from the oldest
   - any conflicts should be resolved in favour of development
   - ideally, there shouldn't be any
1. delete release branches
1. delete `master` branch
1. rename `development -> master`
1. delete `development`

There are also some stale branches. Most probably should be removed. We can address them later

Originally created by @tpluscode at https://github.com/dnnsoftware/Dnn.AdminExperience.Library/issues/154 and https://github.com/dnnsoftware/Dnn.AdminExperience.Extensions/issues/577

**Comment by ohine** [comment]
Comment by @bdukes 

> Sounds good to me

**Comment by ohine** [comment]
Comment by @mitchelsellers 

> I like this idea, but I think if we do this we should take a unified effort to make the structure the same across all of the projects so that we have consistency for community involvement.
> 
> @dnnsoftware/tag any additional thoughts?

**Comment by ohine** [comment]
Comment by @tpluscode 

> take a unified effort to make the structure the same across all of the projects
> 
> Agreed 💯 percent. Like I said on Slack, there is no reinventing anything here. GitHub flow is now a pretty standard approach which, when agreed upon, would be exactly the same in all repos.

**Comment by valadas** [comment]
@ohine Is this issue still relevant now?

**Comment by valadas** [comment]
Closing this issue since last discussion dates from april, I think this is now done right? If not, feel free to reopen
