### ISSUE TITLE
DNN9 Templates  - find / apply /modify

### ISSUE THREAD

**Issue by phantomlady** [dnnsoftware/Dnn.AdminExperience#302]
## Summary
DNN9 Templates  - find / apply /modify  HOW TO?

## Current result (if necessary)
Unable to apply templates to page
Unable to find where the modified templates should be located

## Expected result (if necessary)
Use to find in page settings.

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser

* [x ] Chrome
* [x ] Firefox
* [x ] Safari
* [x ] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
To create a template from an existing page, use the Save as Template on the top of the Pages module as such:
![image](https://user-images.githubusercontent.com/6371568/51512898-33285980-1dd6-11e9-97f4-00d0714002a7.png)

This save a template in the Portals\0\Template (replace 0 with your portal ID) it is an xml file names as .template

To use that template, create a new page and select the template from the dropdown on the bottom left corner:
![image](https://user-images.githubusercontent.com/6371568/51512983-86021100-1dd6-11e9-8c94-b5529da6d1df.png)
