### ISSUE TITLE
Allow Confirm Modal to Accept 1 Option

### ISSUE THREAD

**Issue by SkyeHoefling** [dnnsoftware/Dnn.AdminExperience#303]
## Description of problem
The confirm modal used by the persona bar requires both a confirm and cancel option. Sometimes there is a need to just display the modal and force the user to only click OK. Such as a notification of an action that is going to happen no matter what.

## Description of solution
Updating the confirm function cited below to ignore adding the cancel button if it is not supplied

https://github.com/dnnsoftware/Dnn.AdminExperience/blob/development/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/util.js#L137

## Description of alternatives considered
I considered other APIs such as notify but there is a timer on notify and it goes away after an elapsed time. I use case here is it requires the user to close the modal as they need to acknowledge the notification.

## Screenshots
A standard confirm modal:
![image](https://user-images.githubusercontent.com/17751436/50876190-d66e7d00-1399-11e9-86ef-a740cfe20dbd.png)

A confirm modal with empty string supplied to cancel:
![image](https://user-images.githubusercontent.com/17751436/50876215-ef772e00-1399-11e9-94cf-18199885fef8.png)

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by SkyeHoefling** [comment]
If no one has an issue with us adding this to the library, I am willing to submit a pull request for it

**Comment by valadas** [comment]
I think this is a good idea

**Comment by mtrutledge** [comment]
I agree. Think this is a good idea.

**Comment by mitchelsellers** [comment]
This is a great idea
