### ISSUE TITLE
Platform > PB: Hovering over tooltips generate Javascript errors for maximum update of setState in Card component of react-portal-tooltip

### ISSUE THREAD

**Issue by Mhtshum** [dnnsoftware/Dnn.AdminExperience#319]
## Description of bug
Platform > PB: Hovering over tooltips generate Javascript errors for maximum update of setState in Card component of react-portal-tooltip

## Steps to reproduce
After login as Host
 Hover over the following tooltips:
- Site Settings > Site Behavior > Default Pages > Registration Page
- Site Settings > Site Behavior > User Profiles > Add Field > Required (only reproducible in Platform)
- Site Settings > Site Behavior > User Profiles > Add Field > Data Type (only reproducible in Platform)

## Current result
Tooltip is not appearing and errors in debugger of browser
"export-bundle.js?cdv=52:90 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. "

## Expected result
Tooltip should appear

## Screenshots
![image](https://user-images.githubusercontent.com/43787378/51174646-1a9dd800-18da-11e9-8cb4-7ab272cb6880.png)

## Error log
react-dom.development.js?61bb:55 Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at invariant (react-dom.development.js?61bb:55)
    at scheduleWork (react-dom.development.js?61bb:18406)
    at Object.enqueueSetState (react-dom.development.js?61bb:12313)
    at ProxyComponent.Component.setState (react.development.js?72d0:372)
    at ProxyComponent.updateSize (index.js?5a1b:342)
    at ProxyComponent.updateSize (react-hot-loader.development.js?c2cb:587)
    at ProxyComponent.componentDidUpdate (index.js?5a1b:333)
    at ProxyComponent.componentDidUpdate (react-hot-loader.development.js?c2cb:577)
    at commitLifeCycles (react-dom.development.js?61bb:15976)
    at commitAllLifeCycles (react-dom.development.js?61bb:17262)
invariant @ react-dom.development.js?61bb:55
scheduleWork @ react-dom.development.js?61bb:18406
enqueueSetState @ react-dom.development.js?61bb:12313
Component.setState @ react.development.js?72d0:372
updateSize @ index.js?5a1b:342
getPortalSettings @ react-hot-loader.development.js?c2cb:587
componentDidUpdate @ index.js?5a1b:333
componentDidMount @ react-hot-loader.development.js?c2cb:577
commitLifeCycles @ react-dom.development.js?61bb:15976
commitAllLifeCycles @ react-dom.development.js?61bb:17262
callCallback @ react-dom.development.js?61bb:149
invokeGuardedCallbackDev @ react-dom.development.js?61bb:199
invokeGuardedCallback @ react-dom.development.js?61bb:256
commitRoot @ react-dom.development.js?61bb:17458
completeRoot @ react-dom.development.js?61bb:18912
performWorkOnRoot @ react-dom.development.js?61bb:18841
performWork @ react-dom.development.js?61bb:18749
performSyncWork @ react-dom.development.js?61bb:18723
batchedUpdates$1 @ react-dom.development.js?61bb:18936
batchedUpdates @ react-dom.development.js?61bb:2150
dispatchEvent @ react-dom.development.js?61bb:4899
react-dom.development.js?61bb:15749 The above error occurred in the <Card> component:
    in Card

Consider adding an error boundary to your tree to customize error handling behavior.

## Affected version
* [x] 9.3.0

**Comment by valadas** [comment]
This was fixed with #320 not sure why it did not close automatically, I am closing it.
