### ISSUE TITLE
Site Settings > Site Behavior > Site Aliases: Edit Alias behaves as Add Alias

### ISSUE THREAD

**Issue by anishmishra978** [dnnsoftware/Dnn.AdminExperience#336]
## Description of bug
ISSUE 1: the table with existing aliases has no headers
ISSUE 2:  Site Alias textbox is empty. Because in fact, Edit Alias is working as Add Alias

## Steps to reproduce
##ISSUE 1: the table with existing aliases has no headers
1) Navigate to PB > Site Settings > Site Behavior > Site Aliases
2) Press F5 to refresh

##ISSUE 2:  Site Alias textbox is empty. Because in fact, Edit Alias is working as Add Alias
1) Navigate to PB > Site Settings > Site Behavior > Site Aliases
2) Press F5 to refresh
3) Click Add Alias again
4) Add a new alias, for example platform-latest.dnndev.me. Leave all other fields with default values.
5) Click Save
6) Click the pencil icon to edit the newly created alias

## Current result
1. The table with existing aliases has no headers.
![image](https://user-images.githubusercontent.com/39130449/51430586-9c2b9800-1c43-11e9-8e1b-a0a2f21172a1.png)

2. Site Alias textbox is empty. Because in fact, Edit Alias is working as Add Alias
![image](https://user-images.githubusercontent.com/39130449/51430598-cbdaa000-1c43-11e9-858d-38b8460e3c49.png)

## Expected result
1. header should be present for site Aliases table.
![image](https://user-images.githubusercontent.com/39130449/51430606-e6ad1480-1c43-11e9-879d-ad3e55363d77.png)

2. Site alias should be editable
![image](https://user-images.githubusercontent.com/39130449/51430612-0a705a80-1c44-11e9-9d72-610fe9addcaf.png)
## Affected version
* [ ] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by david-poindexter** [comment]
Merged #343 to release/1.7.0 - manually closing this issue.
