### ISSUE TITLE
Browser debugger errors warnings in When PB > Settings > Servers > System Info

### ISSUE THREAD

**Issue by Mhtshum** [dnnsoftware/Dnn.AdminExperience#338]
## Description of bug
Browser debugger errors warnings in When PB > Settings > Servers > System Info

## Steps to reproduce
1. Login as host
2. Go to PB > Settings > Servers
3. See error

## Current result
Errors and warning in browser console as shown in snapshot

## Expected result
There should not be any warning or errors

## Screenshots
![image](https://user-images.githubusercontent.com/43787378/51436633-e4d26800-1cba-11e9-8ed4-c2319a9f293f.png)

## Error log
VM9092 checkPropTypes.js:19 Warning: Failed prop type: The prop `dispatch` is marked as required in `App`, but its value is `undefined`.
    in App (created by Connect(App))
    in Connect(App) (created by Root)
    in div (created by Root)
    in Root
    in Provider
printWarning @ VM9092 checkPropTypes.js:19
checkPropTypes @ VM9092 checkPropTypes.js:82
validatePropTypes @ react.development.js?72d0:1649
createElementWithValidation @ react.development.js?72d0:1738
React$$1.createElement @ react-hot-loader.development.js?c2cb:984
render @ connectAdvanced.js?fe33:244
hotComponentRender @ react-hot-loader.development.js?c2cb:622
proxiedRender @ react-hot-loader.development.js?c2cb:637
finishClassComponent @ react-dom.development.js?61bb:14301
updateClassComponent @ react-dom.development.js?61bb:14264
beginWork @ react-dom.development.js?61bb:15082
performUnitOfWork @ react-dom.development.js?61bb:17820
workLoop @ react-dom.development.js?61bb:17860
renderRoot @ react-dom.development.js?61bb:17946
performWorkOnRoot @ react-dom.development.js?61bb:18837
performWork @ react-dom.development.js?61bb:18749
performSyncWork @ react-dom.development.js?61bb:18723
requestWork @ react-dom.development.js?61bb:18592
scheduleWork @ react-dom.development.js?61bb:18401
scheduleRootUpdate @ react-dom.development.js?61bb:19069
updateContainerAtExpirationTime @ react-dom.development.js?61bb:19097
updateContainer @ react-dom.development.js?61bb:19154
ReactRoot.render @ react-dom.development.js?61bb:19416
(anonymous) @ react-dom.development.js?61bb:19556
unbatchedUpdates @ react-dom.development.js?61bb:18952
legacyRenderSubtreeIntoContainer @ react-dom.development.js?61bb:19552
render @ react-dom.development.js?61bb:19613
(anonymous) @ main.jsx?ee95:20
./src/main.jsx @ servers-bundle.js?cdv=52:1785
__webpack_require__ @ servers-bundle.js?cdv=52:725
fn @ servers-bundle.js?cdv=52:102
0 @ servers-bundle.js?cdv=52:2050
__webpack_require__ @ servers-bundle.js?cdv=52:725
(anonymous) @ servers-bundle.js?cdv=52:792
(anonymous) @ servers-bundle.js?cdv=52:795
react-dom.development.js?61bb:506 Warning: Unsupported style property margin-right. Did you mean marginRight?
    in button (created by Button)
    in Button (created by App)
    in div (created by PersonaBarPageHeader)
    in div (created by PersonaBarPageHeader)
    in PersonaBarPageHeader (created by App)

## Additional context
Setup Development environment by setting up react applications, i.e. Site Settings & export bundle, in your local platform or evoq instance

## Affected version
* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1

**Comment by daguiler** [comment]
Not sure why this wasn't closed by #339. Closing manually.

**Comment by valadas** [comment]
Yeah, there has been a couple ones like that, I don't know if it may be because of the release branch (it would close it when merging into the default branch)?

**Comment by ohine** [comment]
It happens on development too, I closed about a dozen issues that linked to merged pull requests before even creating the release branch

**Comment by valadas** [comment]
Strange, any settings in the repository control that?
