### ISSUE TITLE
Themes labels are missing

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.AdminExperience#340]
## Description of bug
Themes labels are missing

## Current result
![image](https://user-images.githubusercontent.com/6371568/51444532-af337c00-1cc6-11e9-89b8-dbadeed5d53a.png)

## Expected result
![image](https://user-images.githubusercontent.com/6371568/51444556-f588db00-1cc6-11e9-8b9c-6d257f44af58.png)

**Comment by ohine** [comment]
Closing issue after merging into release/1.7.0
