### ISSUE TITLE
Settings > Site Settings > Languages > Activate Pages in This Language toggle button is not Set ON/OFF

### ISSUE THREAD

**Issue by Mhtshum** [dnnsoftware/Dnn.AdminExperience#348]
## Description of bug
Settings > Site Settings > Languages > Activate Pages in This Language toggle button is not Set ON/OFF

## Steps to reproduce
1) Navigate to Site Settings -> Languages 
2) Click on the page icon (i.e. 4th icon) of the newly added language (Translate Page Content page is displayed) 
3) Click on Activate Pages in This Language toggle button to set to ON 

## Current result
Toggle button is not setting ON. 
But if we refresh the page, we see that toggle button is set to ON 

## Expected result
Toggle button should be set ON/OFF without refreshing the page or using back button

## Additional context
Newly added language is enabled 
Enable the Content Localization and Make All Pages as translatable 

## Affected version
* [x] 9.3.0

**Comment by david-poindexter** [comment]
Merged to release/1.7.0 - manually closing issue.
