### ISSUE TITLE
Enable Localized Content button not changing to the Disable 

### ISSUE THREAD

**Issue by Mhtshum** [dnnsoftware/Dnn.AdminExperience#353]
## Description of bug
Settings > Site Settings > Languages > Enable Localized Content button not changing to the Disable Localized Content automatically

## Steps to reproduce
1) Navigate to Site Settings -> Languages 
2) Make Allow Content Localization toggle button set to ON 
3) Click on Save button 
4) Click on Enable Localized Content 
5) Set the Make All Pages Translatable toggle button to ON 
6) Click on Enable Localized Content 

## Current result
Enable Localized Content button is displayed on the Languages page. 
If we refresh the page, then only Enable Localized Content button changes to Disable Localized button 

## Expected result
Disable Localized Content button should be displayed once all the pages gets translated i.e. after step 6. 
We should not do extra refresh to change the button name from Enable Localized Content to Disable Localized Content 

## Additional context
Newly added language is enabled 

## Affected version
* [x] 9.3.0

**Comment by valadas** [comment]
Closing manually since the PR got merged.
