### ISSUE TITLE
Intermittent Tooltip Animation

### ISSUE THREAD

**Issue by mikesmeltzer** [dnnsoftware/Dnn.AdminExperience#355]
## Description of bug

Tooltips within some of the PersonaBar extensions have an intermittent animation on hover.

## Steps to reproduce

1. Open up a Persona Bar extension screen
2. Hover over a tooltip
3. Hover over another tooltip
4. Try steps 2 and 3 on different screens 
5. The Status and Public fields on the Roles screen are consistently showing the animation when hovering the mouse back and forth between the 2 tooltip icons.

## Current result

The carrot on the bottom of the tooltip is intermittently animating in from the left of the element to the center.

## Expected result
The carrot should not have an animation and should be static on the tooltip.

## Affected version
* [x] 9.3.0 RC
* [x] 9.2.2

## Affected browser

* [ x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [x ] Edge

**Comment by valadas** [comment]
This PR should resolved that issue and make them accessible too https://github.com/dnnsoftware/Dnn.React.Common/pull/212

**Comment by david-poindexter** [comment]
Looks like we can close this issue then @valadas?

**Comment by valadas** [comment]
Yes sir
