### ISSUE TITLE
Browser warning under PB > Settings > Site Settings > Language(tab)

### ISSUE THREAD

**Issue by Mhtshum** [dnnsoftware/Dnn.AdminExperience#357]
## Description of bug
Browser warning under PB > Settings > Site Settings > Language(tab). Various warnings on clicking

## Steps to reproduce
Login as host
1. Go to 'PB > Settings > Site Settings > Language' then click on last icon in lanaguages grid
2. See error

checkPropTypes.js?a15c:19 Warning: Failed prop type: Invalid prop `resxBeingEditedDisplay` of type `string` supplied to `LanguageInfoView`, expected `function`.
    in LanguageInfoView (created by EditLanguagePanel)
    in EditLanguagePanel (created by Connect(EditLanguagePanel))
    in Connect(EditLanguagePanel) (created by App)
    in div (created by s)

And when clicking on "Add new Language"
react.development.js?72d0:225 Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `LanguageEditor`. See https://fb.me/react-warning-keys for more information.
    in div (created by LanguageEditor)
    in LanguageEditor (created by Connect(LanguageEditor))
    in Connect(LanguageEditor) (created by LanguagesPanel)
    in div (created by Motion)

While there is also tooltip warning which would be resolved with #320 

## Current result
Warnings for
- Unique key for LanguageEditor
- type error resxBeingEditedDisplay

## Expected result
These warning should not be generated

## Screenshots
![image](https://user-images.githubusercontent.com/43787378/51627916-c9db4e80-1f6d-11e9-9ab1-c59dbd65fcd7.png)

## Error log
Mentioned above

## Additional context
Setup development environment with Export-bundles and Site-settings

* [x] 9.3,0

**Comment by valadas** [comment]
Closing since it is merged
