### ISSUE TITLE
Site Settings > Languages > Add Language

### ISSUE THREAD

**Issue by anishmishra978** [dnnsoftware/Dnn.AdminExperience#361]
## Description of bug
An empty row with dashes is created and remains after Cancel

## Steps to reproduce
1) Navigate to PB > Site Settings > Languages
2) Click on Add New Language
3) Click Cancel

## Current result
An empty row with dashes is created and remains after Cancel

## Expected result
Issue should not occur

## Affected version
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
Manually closing since PR got merged
