### ISSUE TITLE
Site Settings > Site Behavior > User Profiles > Add Field

### ISSUE THREAD

**Issue by anishmishra978** [dnnsoftware/Dnn.AdminExperience#365]
## Description of bug
An empty row with dashes and icons is created and remains after Canceling adding new field.

## Steps to reproduce
1) Navigate to PB > Site Settings > Site Behavior > User Profiles
2) Click on Add Field
3) Click Cancel

## Current result
 An empty row with dashes and icons is created and remains after Cancel

## Expected result
No issues should occur.

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
Closing manually, PR got merged
