### ISSUE TITLE
Wrong text in welcome email when users are added manually

### ISSUE THREAD

**Issue by daguiler** [dnnsoftware/Dnn.AdminExperience#367]
## Description of bug
When a new user is added **manually** by the host (not via self registration), and the user registration mode is set to **Private**, the user gets an email with following text:
> Your account details will be reviewed by the website Administrator and you will receive a notification upon account activation.

This is not accurate because users are automatically approved when manually added by the host, so no further notification is sent. I think we should send the Public registration message instead:
> We are pleased to advise that you have been added as a Registered User to My Website.

If the site's registration mode is set to **Public**, then the above issue does not occur: the second message is sent in the email.
So when users are added manually by the host, we are sending one message or the other depending on the user registration mode, which is wrong. We should always send the second one.

## Steps to reproduce
1. Fresh 9.3.0 RC install
2. Log in as host
3. Open PB > Settings > Servers > Server Settings > SMTP Server
4. Setup correct SMTP values
5. Open PB > Settings > Security > Member Accounts > Registration Settings
6. Set **User Registration** to **Private**
7. Open PB > Manage > Users
8. Add a new user. Make sure to specify a valid email address and check the **Send An Email To New User** option
9. Click **Save** to add the new user

## Current result
The user gets a welcome email with following text:
> Your account details will be reviewed by the website Administrator and you will receive a notification upon account activation.

## Expected result
User should get a welcome email with following text:
> We are pleased to advise that you have been added as a Registered User to My Website.

## Affected version

* [x] 9.3.0 RC

**Comment by valadas** [comment]
Merged

**Comment by daguiler** [comment]
Reopening (I think this one was incorrectly closed)

**Comment by valadas** [comment]
I can no longer reproduce in 9.4.0 RC and I think it was resolved in Platform by https://github.com/dnnsoftware/Dnn.Platform/pull/2847 closing this issue.
