### ISSUE TITLE
Missing border-bottom on all dropdown fields in Site Settings > Site Behavior > DEFAULT PAGES

### ISSUE THREAD

**Issue by david-poindexter** [dnnsoftware/Dnn.AdminExperience#368]
## Description of bug
Missing border-bottom style on all dropdown fields in Site Settings > Site Behavior > DEFAULT PAGES

## Steps to reproduce
List the steps to reproduce the behavior:
1. Login as host
2. Go to **Site Settings** in PersonaBar
3. Select **Site Behavior** tab
4. View **DEFAULT PAGES** tab
5. View all dropdown fields

## Current result
Missing bottom border on dropdown fields

## Expected result
Should have a bottom border

## Screenshots
![screencapture_ 2019-01-29 07 43 pm _2148](https://user-images.githubusercontent.com/4568451/51950370-3b981a00-23fe-11e9-9233-09e9e1b4311c.jpg)

## Error log
n/a

## Additional context
n/a

## Affected version
* [x] 9.3.0 RC1
* [ ] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
I think I did this fix in the past, let me search for it...

**Comment by valadas** [comment]
Yeah, here https://github.com/dnnsoftware/Dnn.React.Common/pull/190/files

**Comment by david-poindexter** [comment]
This may be an issue with the component.  See the following screenshots.  The first one is the way it is now.

![screencapture_ 2019-01-29 07 57 pm _2149](https://user-images.githubusercontent.com/4568451/51950892-5a97ab80-2400-11e9-8d63-f4d7b3d73255.jpg)

Removing the border fixes the issue as shown in this one.
![screencapture_ 2019-01-29 07 58 pm _2150](https://user-images.githubusercontent.com/4568451/51950921-74d18980-2400-11e9-8ead-370f6001d8e3.jpg)

**Comment by david-poindexter** [comment]
Ah, okay @valadas - I do remember seeing that.  So it appears we may have a build issue then with RC1.

**Comment by david-poindexter** [comment]
It was determined this issue is a viable issue, and slightly different than the one resolved previously by @valadas.  It is not a build issue.

**Comment by mtrutledge** [comment]
It looks like this comes from the style.less file in Dnn.React.Common/src/PermissionGrid/RoleGroupFilter/style.less. the one in style.less in src/PagePicker currently has this as the .collapsible-content
```
.collapsible-content {
        position: absolute;
        padding: 0;
        top: 38px;
        width: 100%;
        box-sizing: border-box;
        background-color: @white;
        z-index: 1000;
        -webkit-box-shadow: 0px 0px 20px 0px rgba(0, 0, 0, 0.2);
        -moz-box-shadow: 0px 0px 20px 0px rgba(0, 0, 0, 0.2);
        box-shadow: 0px 0px 20px 0px rgba(0, 0, 0, 0.2);
        border: 0px;
    }
```

Should the border be set to 0px for the RoleGroupFilter/style.less as well?

**Comment by mtrutledge** [comment]
PR for this submitted in React Common:
https://github.com/dnnsoftware/Dnn.React.Common/pull/218

**Comment by david-poindexter** [comment]
Thank you @mtrutledge - I'll go ahead and close this issue.
