### ISSUE TITLE
'Use SSL for cache synchonization' in UI does not match database

### ISSUE THREAD

**Issue by OllyHodgson** [dnnsoftware/Dnn.AdminExperience#37]
## Description of bug
The 'Use SSL for cache synchonization' switch does not always match the setting value in the database HostSettings table. Switching it on enables the setting, and the change is saved to the database, but the next time you visit the Performance pane, the switch says "Off".

## Steps to reproduce
List the steps to reproduce the behavior:

1. Log into a DNN 9.2.1 install as a Super User
2. In the PersonaBar, click Cog (Settings), then Servers
3. Click Server Settings, then Performance
4. Set _SSL for Cache Synchronization_ to **On**
5. Click Save
6. Refresh the page
7. Navigate back into the Performance pane
8. Note that _SSL for Cache Synchronization_ is **Off**
9. In the PersonaBar, click Cog (Settings), then SQL Console
10. Enter `select * from HostSettings where SettingName = 'UseSSLForCacheSync'`
1. Note that `SettingValue` is `true`.

## Current result

The setting is correctly stored in the database HostSettings table, but is not correctly reflected in the UI.

## Expected result
The setting is correctly stored in the database HostSettings table, and is correctly reflected in the UI.

## Affected version

* [x] 9.2.1
* [x] 9.2

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Internet Explorer

**Comment by valadas** [comment]
This would need to be tested on Dnn 9.3.0 before any code, but I assigned it to 9.3.1 milestone.

**Comment by sleupold** [comment]
question is, whether the setting value just doesn't get loaded in the PB module or is not saved correctly.

**Comment by valadas** [comment]
I am able to reproduce, working on it now

**Comment by valadas** [comment]
PR Merged
