### ISSUE TITLE
Merging Dnn.React.Common into Dnn.AdminExperience

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.AdminExperience#375]
## Description of problem
Merging Dnn.React.Common into Dnn.Admin experience would help simplify developement.

## Description of solution
We need to move the files into this repository in it's own folder and do adjustments to CI maybe.

## Additional context
This is the result of the discussions in https://github.com/dnnsoftware/Dnn.Platform/issues/2436 and https://github.com/dnnsoftware/Dnn.Platform/issues/2556 and it appears we have a consensus on this part.

It may required adjustment to CI and https://github.com/nbrane/Dnn.DevelopmentConfig

**Comment by ohine** [comment]
This is closed when #438 is merged.
