### ISSUE TITLE
Implement Yarn workspaces in the new merged repository

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.AdminExperience#376]
Implementing Yarn workspaces in the new merged repository would save a lot of build time and disc space required.

## Description of problem
Currently each single module has it's own node_modules folder and they all have 90% of the same packages in them, this is a lot of duplication, it takes a lot of time to build and uses huge disc spaces.

## Description of solution
Yarn workspaces is a way to have a common node_modules folder for each project in a common external directory. Each project then reference that common folder and does nothing if the package is already there or adds it if needed. This basically deduplicates same dependencies and nothing more. It is simple to implement, 1 line to add per project and one common config file to setup the workspace.

## Additional context
Doing #375 first would deduplicate even more

**Comment by ohine** [comment]
This is closed when #693 is merged.

**Comment by ohine** [comment]
This is now merged with PR #438
