### ISSUE TITLE
DNN Platform RC1 > Persona Bar > Settings > Site Settings > Error adding User Profile field

### ISSUE THREAD

**Issue by DinKumar** [dnnsoftware/Dnn.AdminExperience#378]
## Precondition
1. Latest DNN Platform RC1 is installed 
2. Host user credentials are available

## Description of bug
Blank screen is displayed when user clicks on Next button while adding User Profile field.

## Steps to reproduce
1. Login to DNN Platform with Host user credentials 
2. Go to Persona Bar > Settings > Site Settings Then Click on Site Behavior tab 
3. Click on User Profiles tab 
4. Click on USER PROFILE FIELDS section> Add Field link for. Enter valid inputs for following fields 
a. Field Name* TESTING 
b. Property Category* QA 
c. Default Value Version 
d. Required and Visible TRUE 
e. Default Visibility All Users 
f. Data Type* as List 
g. Length as 10 
5. Click on Next 

## Current result
Application displays blank screen and console errors are displayed.

## Expected result
Application should display manage list entries section when user clicks on Next button. There should not be any console error.

## Screenshots
![blankscreenadduserfield](https://user-images.githubusercontent.com/40901826/52231216-617e5c80-28df-11e9-9b04-8872f11c6d2a.png)

## Error log
export-bundle.js?cdv=52:90 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at export-bundle.js?cdv=52:90
    at i (export-bundle.js?cdv=52:90)
    at Nr (export-bundle.js?cdv=52:90)
    at _ (export-bundle.js?cdv=52:90)
    at h (export-bundle.js?cdv=52:90)
    at export-bundle.js?cdv=52:90
    at na (export-bundle.js?cdv=52:90)
    at pa (export-bundle.js?cdv=52:90)
    at qa (export-bundle.js?cdv=52:90)
    at Qa (export-bundle.js?cdv=52:90)

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version
* [x] Platform RC1

## Affected browser
* [x ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
Closing, PR fixed it.
