### ISSUE TITLE
DNN Platform RC1 > Persona Bar > Settings > Site Settings > Changes are not reverted in case of Cancel in Site Info edit

### ISSUE THREAD

**Issue by DinKumar** [dnnsoftware/Dnn.AdminExperience#379]
## Precondition
1. Latest DNN Platform is installed 
2. Host user credentials are available

## Description of bug
When user clicks on cancel button in Site Info then original field values is not getting reverted.

## Steps to reproduce
1. Login to DNN Platform with Host user credentials 
2. Go to Persona Bar > Settings > Site Settings 
3. On Site Info tab, edit the any of the fields like 
a. Site Title 
b. Site Description 
C. Site Keywords. 
4. Click on Cancel 
5. Click on Yes on confirmation pop up window

## Current result
Edited field values are not reverted to original values.

## Expected result
When user clicks on cancel then edited values should not be retained and original field values should be displayed.

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] Platform RC1
* [] 9.2.2
* [] 9.2.1
* [] 9.2
* [] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
Closing, PR fixed it
