### ISSUE TITLE
DNN Platform RC1 > Persona Bar > Settings > Site Settings > Site Behavior > Default Pages > Dropdown fields are not getting populated

### ISSUE THREAD

**Issue by DinKumar** [dnnsoftware/Dnn.AdminExperience#380]
## Precondition
1. Latest DNN Platform is installed 
2. Host user credentials are available
## Description of bug
Dropdown fields on DEFAULT PAGES tab are not getting populated when user clicks on the fields.

## Steps to reproduce
1. Login to DNN Platform with Host user credentials 
2. Go to Persona Bar > Settings > Site Settings > Site Behavior 
3. On Default Pages tab, click on any of the fields dropdown. E.g. Splash Page, Home page etc. 

## Current result
Application tries to fetch the results but list is not populated and displayed.

## Expected result
Selected field's dropdown list should be displayed.

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] Platform RC1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
https://github.com/dnnsoftware/Dnn.React.Common/pull/221 fixed this one
