### ISSUE TITLE
DNN Platform RC1 > Persona Bar > Settings > Site Settings > Child site data is not loading

### ISSUE THREAD

**Issue by DinKumar** [dnnsoftware/Dnn.AdminExperience#382]
## Precondition
1. DNN Platform RC1 is installed 
2. Host user credentials are available 
3. Child site is added

## Description of bug
Child site data is not loading on Site Settings page.

## Steps to reproduce
1. Log in as Host user in DNN Platform 
2. Go to Persona Bar > Settings > Site Settings 
3. Select the Child site from EDITING SITE drop-down list 

## Current result
Site info and other settings related to selected child site is not displayed.

Application behaves strange when user selects child site to edit the site info. Select the child site then again default site and again select child site. Application continuously displays progress bar and doesn't load the selected sites information.

## Expected result
Once user selects the child site from Editing Site drop-down list application should display the selected sites data/settings.

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] Platform RC1
* [] 9.2.2
* [] 9.2.1
* [] 9.2
* [] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by mikebigun** [comment]
Dear community, I started working on this problem, please skip it to avoid double efforts on it.

**Comment by valadas** [comment]
Closing, PR merged
