### ISSUE TITLE
DNN Platform RC1 > Persona Bar > Manage > Users> Console Errors on Add User with existing username

### ISSUE THREAD

**Issue by DinKumar** [dnnsoftware/Dnn.AdminExperience#383]
## Precondition
1. Install Platform RC1
2. Host user credentials are available 
3. Authorized user with email id as username OR normal username is created
## Description of bug
Application throws 500 (Internal Server Error) while adding user with existing username.

## Steps to reproduce
1. Login to DNN Platform as host user /Administrator user 
2. Go to Persona Bar > Manage > Users 
3. Click on Add User button 
4. Fill valid inputs on Add User screen except User Name-> Add existing username 
5. Click on Save button

## Current result
Application displays error message which is expected but console error is also displayed: 
POST http://dw1.eu.aureacentral.com:21030/API/PersonaBar/Users/CreateUser 500 (Internal Server Error) 

## Expected result
Application displays error message for username is already in use and there should not be any console error.

## Screenshots
![consoleerrorforexistinguser](https://user-images.githubusercontent.com/40901826/52247532-42e48980-2910-11e9-9bc2-8ea3a3cee113.png)

## Error log
jquery.js?cdv=52:11 POST http://168.61.157.87/API/PersonaBar/Users/CreateUser 500 (Internal Server Error)

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] Platform RC1
* [ ] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by Mhtshum** [comment]
I think it is correct as 
Because api call is throwing as error for existing user with 500 code. 

Please check
https://github.com/dnnsoftware/Dnn.AdminExperience/blob/f305365117c77941abdcad697c2dd644f0e5d103/Extensions/Manage/Dnn.PersonaBar.Users/Components/RegisterController.cs#L106

**Comment by daguiler** [comment]
It should be a HTTP 400 (Bad Request) response instead of an internal server error.
Which will also generate a error in console, but at least it's standards compliant.

**Comment by daguiler** [comment]
Closing as PR was also closed.
