### ISSUE TITLE
DNN Platform RC1 > Persona Bar > Settings > Connectors > Console Errors

### ISSUE THREAD

**Issue by DinKumar** [dnnsoftware/Dnn.AdminExperience#384]
## Precondition
1. Install latest Platform 
2. Host user credentials are available

## Description of bug
Console error is displayed when Connectors page is accessed by the host user.

## Steps to reproduce
1. Login to DNN Platform as host user 
2. Go to Persona Bar > Settings > Connectors 

## Current result
Console errors are displayed: 
http://dw1.eu.aureacentral.com:21030/DesktopModules/admin/Dnn.PersonaBar/scripts/contrib/css/personaBarDialog.css?function(id,%20url)%20{%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20(url.indexOf(%27?%27)%20===%20-1%20?%20%27?%27%20:%20%27&%27)%20+%20urlArgs;%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20} net::ERR_ABORTED 404 (Not Found)

## Expected result
There should not be any console error while accessing Connectors module.

## Screenshots
![platform-connectors-consoleerror](https://user-images.githubusercontent.com/40901826/52247856-8a1f4a00-2911-11e9-952d-c4456818edcd.png)

## Error log
http://dw1.eu.aureacentral.com:21030/DesktopModules/admin/Dnn.PersonaBar/scripts/contrib/css/personaBarDialog.css?function(id,%20url)%20{%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20(url.indexOf(%27?%27)%20===%20-1%20?%20%27?%27%20:%20%27&%27)%20+%20urlArgs;%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20} net::ERR_ABORTED 404 (Not Found)

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] Platform RC1
* [ ] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
Closing, PR merged
