### ISSUE TITLE
Personabar Users control panel blank for Edge Browser

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.AdminExperience#390]
@skarpik commented on [Thu Feb 07 2019](https://github.com/dnnsoftware/Dnn.Platform/issues/2581)

## Description of bug
DNN 9.3.0 rc1 
Users control panel is blank when using Edge browser. Works perfectly for Chrome and Firefox. DNN installation was "direct out of the box" (i.e. no extensions installed).

## Steps to reproduce
List the steps to reproduce the behavior:
1. Log on as SuperUser
2. Click on Manage Users (on the Personabar)
3. The control panel that pops out is blank.

## Current result
Unable to edit user info because the users control panel is blank

## Expected result
Should work on Edge just like it does on Chrome and Firefox.

## Screenshots
n/a

## Error log
No errors

## Additional context
none

## Affected version

* [x] 9.3.0
* [] 9.2.2
* [] 9.2.1
* [] 9.2
* [] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
Moving this issue to AdminExperience repository.

**Comment by valadas** [comment]
I was able to reproduce

**Comment by valadas** [comment]
I get this in the console:
![image](https://user-images.githubusercontent.com/6371568/52786767-d103f280-3029-11e9-9e70-6b9481eb7dd5.png)
When clicking the link, it just brings me to the end of the html document, so not sure where that error is in reality.

A quick google search points me to https://stackoverflow.com/questions/53628191/edge-script1028-expected-identifier-string-or-number

It looks like there would be modern javascript rest operation that is not supported in Edge yet. I guess the first step would be to compare the babel config with other modules.

**Comment by valadas** [comment]
Well, I have tried multiple configurations of eslint, webpack and babel and all I can achieve is break the build. I gonna need help on this one, my guess is that there is something wrongly configured with the _exportables, this is the only module that has a part of it exportable. I don't know enough about how that works to create a fix. Any hints are welcome.

**Comment by mtrutledge** [comment]
@valadas is the`@babel/plugin-transform-spread` and `@babel/plugin-proposal-object-rest-spread` included in the babelrc config and package.json for that project? The other thing that I have seen that could cause a potential issue is when there is a trailing comma on an object definition like
```
var e = { 
i: 1,
a: 2, <-- trailing comma
}
```

**Comment by valadas** [comment]
I added @babel/plugin-transform-spread and recompiled which did not change the bug. I have not spotted an extra comma, but edge devtools just indicates the error is at index.html line 20 which is a blank line and not even part of the bundle...

**Comment by mtrutledge** [comment]
I wonder if edge needs a polyfill. Try adding @babel/polyfill and at the top of the main jsx component add ‘import @babel/polyfill;’

**Comment by valadas** [comment]
Just tried it and it gives the same issue. What really makes it difficult is Edge does not give the correct location in code for the error being reported. It just points to the end of the html document. Edge devtools are not the best...

**Comment by mtrutledge** [comment]
Hmm. Running out of ideas over here.

**Comment by mtrutledge** [comment]
Try disabling compatibility mode

<meta http-equiv="X-UA-Compatible" content="IE=edge" />

**Comment by valadas** [comment]
Yeah, spent many hours yesterday, I tried to isolate components (remove everything I could) but I was getting other errors relating to the link between this and the _exportables one. Not sure how to bypass that one without breaking everything... My goal was to eleminate everything and add back piece by piece until the trouble occurs.

**Comment by mtrutledge** [comment]
This post says that a reserved javascript keyword in a JSON object can also cause the error
http://mikemclin.net/fixing-error-script1028-expected-identifier-string-or-number/

**Comment by valadas** [comment]
Yep, yet very hard to spot since Edge just throws the error in the end of the html (no location in actual javascript)

**Comment by daguiler** [comment]
I couldn't make Edge browse my local dnndev.me domain, so I tried Internet Explorer 11. I saw the blank users screen, and also I got this in the console:
![image](https://user-images.githubusercontent.com/30123437/53041069-ca2e1300-3461-11e9-8ae5-6a77a1ef39f5.png)

When I click on that UsersCommon.js error, I'm redirected to webpack:///localization/index.jsx, where line 3 is highlighted:
![image](https://user-images.githubusercontent.com/30123437/53041159-03ff1980-3462-11e9-9981-a7bd22abbf5c.png)

**Comment by bdukes** [comment]
Can you find that code in the compiled `UsersCommon.js`?  I tried to [replicate the babel config](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAVxsANsZBTAznAZlCEOAIiVS2IG4AoagYwgDst4psAPOAXjgG9q4cAOYYYACgDWGAJ4BKPgMFwUouCAgATBCoByAQxAZucAOQBVLBihYTNAJBsYCKI0TI0mLADoRMAEocYupaugYYADRwUnI0ggC-1AnUGOyQsHAaGLh62qwclEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Cenv&prettier=false&targets=&version=7.3.3), and it looked like that would be successfully converted from a getter to a property.  (BTW, are we specifying a browserslist anywhere, or just using the default _env_ config that transpiles everything?)

**Comment by valadas** [comment]
@daguiler it looks like this is just Edge thowing the error location at any random place, that file is pretty much the same on all the other modules and they work in Edge

**Comment by daguiler** [comment]
I think the browser is pointing the error correctly. Here's UsersCommon.js at that location:

![image](https://user-images.githubusercontent.com/30123437/53044484-e8980c80-3469-11e9-98ee-dce3f872a9fe.png)

```javascript
var B={get:e=>S.getResx("Users",e)}
```

Which is different from plain JS:

```javascript
var resx = {
  get: function get(key) {
    var moduleName = 'Users';
    return _utils.default.getResx(moduleName, key);
  }
};
```

**Comment by daguiler** [comment]
It seems IE 11 doesn't understand arrow functions, but should work in Edge 17 and above.
https://kangax.github.io/compat-table/es6/

**Comment by bdukes** [comment]
I wonder if the babel config is out-of-sync for that module or something.  That arrow function is definitely not supported in IE 11 (but, as @daguiler just said, [kangax](https://kangax.github.io/compat-table/es6/#test-arrow_functions) shows it's supported by Edge 15+)

**Comment by valadas** [comment]
Well the arrow function should not be in the minified js file, that is a problem, the UsersCommon.js file is not correctly transpiled then. I think the webpack config is wrong here https://github.com/dnnsoftware/Dnn.AdminExperience/blob/b9bda245e8381811733b897cfae6153f26a55203/Extensions/Manage/Dnn.PersonaBar.Users/Users.Web/src/_exportables/webpack.config.js#L9-L20

It should be options, not query...
Let me try that

**Comment by valadas** [comment]
Scratch that code reference, got it from an old commit for some reason... Still investigation

**Comment by valadas** [comment]
Just FYI, PR #406 fixed it for me for Edge, the IE11 error is probably something else.

**Comment by bdukes** [comment]
In #424 I have a fix that transpiles arrow functions, but it looks like there are still other Babel issues, e.g. some `Object.assign` calls in `user-bundle.js` aren't getting polyfilled.  There are definitely some weird issues around babel config, but I can't pinpoint what's missing

**Comment by valadas** [comment]
Merged
