### ISSUE TITLE
Persona Bar slide effect on every refresh

### ISSUE THREAD

**Issue by daguiler** [dnnsoftware/Dnn.AdminExperience#393]
## Description of bug
On every roundtrip to the server, the PersonaBar menu is loaded again. It usually takes a few moments to load and it remains hidden until it does. Then it shows with this sliding effect that moves the entire page to the right. This is very annoying and may even make the user click on the wrong UI components.

## Steps to reproduce
1. Login to DNN as a host
2. Observe the PersonaBar slide effect when it loads.

## Current result
The whole page is moved to the right.

## Expected result
It would be a much better UX if the page didn't move all the time because of the PB.

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer
* [X] Edge

**Comment by valadas** [comment]
Closing since it is merged
