### ISSUE TITLE
Correct CSS path for tags-input.css inside tagsinput.js

### ISSUE THREAD

**Issue by Mhtshum** [dnnsoftware/Dnn.AdminExperience#398]
## Description of bug
Path of tags-input.css is not correct and throwing exception in browser console for Evoq application. When PB > Content > Assets.

While tags-input.css seems to be not used in Platform application

## Steps to reproduce
Content\Assets

## Current result
In Browser debugger error

## Expected result
There should not be any error

## Error log
VM502 util.js:479 GET http://engage.dnndev.me/DesktopModules/admin/Dnn.PersonaBar/scripts/contrib/css/tags-input.css?function(id,%20url)%20{%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20(url.indexOf(%27?%27)%20===%20-1%20?%20%27?%27%20:%20%27&%27)%20+%20urlArgs;%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20} net::ERR_ABORTED 404 (Not Found)

## Affected version

* [x] 9.3.0

**Comment by valadas** [comment]
Closing, PR merged
