### ISSUE TITLE
Page localization settings tooltips

### ISSUE THREAD

**Issue by mikebigun** [dnnsoftware/Dnn.AdminExperience#414]
## Description of bug
Users are experiencing some problems when configuring module localization settings. To prevent confusion, need to add more explanation to the page localization tab. Good to have tooltips added and provide details what particular setting does.

## Steps to reproduce
1. Go to `Settings -> Site Settings`
2. Go to `Languages`
3. Add one or more languages, i.e. fr-FR, it-IT
4. Enable Content Localization
5. Translate all default pages 
6. Go to `Home` Page settings
7. Go to `Localization` Tab

## Current result
Currently, page localization tab contains set of modules configurations (checkboxes and links) which are not well-descriptive. It is not always clear what all of these settings means. Due to lack of information it causes confusion and after the changes users are experiencing unexpected behavior, i.e. when localizing or de-localizing modules.

## Expected result
Would be good to have tooltips on hover describing what particular checkbox/link does. That will help users to make proper configurations. See screenshot below with an expected result. 

## Screenshots
![image](https://user-images.githubusercontent.com/22524011/53508855-41e3e980-3ac3-11e9-8fa7-2583a50acdcd.png)

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by valadas** [comment]
Closed by #723
