### ISSUE TITLE
Settings - Site Settings - Table Columns are displayed after page refresh

### ISSUE THREAD

**Issue by anishmishra978** [dnnsoftware/Dnn.AdminExperience#416]
## Description of bug
Settings - Site Settings - Table Columns are displayed after page refresh

Expected Result: PAGES,TRANSLATED and ACTIVE Columns should be displayed in the Languages section without any page refresh.

Actual Result: PAGES,TRANSLATED and ACTIVE Columns are displayed after page refreshment is done.

## Steps to reproduce
Navigate to Settings -> Site Settings -> Click on Languages 
Click on Allow Content Localization toggle button 
Click on Save button 
Click on Enable Localized Content 
Click on Enable Localized Content button 

## Current result
PAGES,TRANSLATED and ACTIVE Columns are displayed after page refreshment is done.

## Expected result
PAGES,TRANSLATED and ACTIVE Columns should be displayed in the Languages section without any page refresh. 

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
Merged
