### ISSUE TITLE
Settings > Site Settings > Languages > Enable Localized Content button not changing to the Disable Localized Content automatically	

### ISSUE THREAD

**Issue by anishmishra978** [dnnsoftware/Dnn.AdminExperience#417]
## Description of bug
Settings > Site Settings > Languages > Enable Localized Content button not changing to the Disable Localized Content automatically

Expected Result: Disable Localized Content button should be displayed once all the pages gets translated i.e. after step 6.
We should not require to do extra refresh to change the button name from Enable Localized Content to Disable Localized Content

Actual Result: Enable Localized Content button is displayed on the Languages page.
If we refresh the page, then only Enable Localized Content button changes to Disable Localized button

## Steps to reproduce
1) Navigate to Site Settings -> Languages 
2) Make Allow Content Localization toggle button set to ON 
3) Click on Save button 
4) Click on Enable Localized Content 
5) Set the Make All Pages Translatable toggle button to ON 
6) Click on Enable Localized Content

## Current result
Enable Localized Content button is displayed on the Languages page. 
If we refresh the page, then only Enable Localized Content button changes to Disable Localized button

## Expected result
Disable Localized Content button should be displayed once all the pages gets translated i.e. after step 6. 
We should not do extra refresh to change the button name from Enable Localized Content to Disable Localized Content

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
* [x] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
Merged
