### ISSUE TITLE
Remove usage of inline-source-map

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.AdminExperience#419]
## Description of problem
Some modules use the inline-source-map devtool. This maps the transpiled minified javascript back to the original modern source code to make it easier to find where an error occurs in production. Using inline-source-map includes the whole transpiled + source code in the resulting bundle which makes is unnecessary huge.

## Description of solution
The source map should be in a separate file, browser devtools will use it only if open but the normal visitors will not load that map file. This would save bandwidth and probably improve performance. The only change needed is replacing inline-source-map for source-map and ensuring the .map file is included in the module packaging together with the bundle file.

## Screenshots
inline-source-map:
![image](https://user-images.githubusercontent.com/6371568/53548777-5abec000-3b00-11e9-8102-6ba60b423d63.png)

source-map
![image](https://user-images.githubusercontent.com/6371568/53549342-f866bf00-3b01-11e9-95cf-1ca3e0e53a64.png)

**Comment by mitchelsellers** [comment]
This is an awesome suggestion!

**Comment by valadas** [comment]
PR Merged
