### ISSUE TITLE
DNN Platform RC2 > Persona Bar > Manage > Sites page is displayed blank with console errors in IE11

### ISSUE THREAD

**Issue by DinKumar** [dnnsoftware/Dnn.AdminExperience#427]
## Precondition
1. Install latest Platform RC Build
2. Host user credentials are available to access the application

## Description of bug
Sites page is displayed blank in IE11. 

## Steps to reproduce
1. Access DNN Platform application in IE11 browser.
2. Login as host user.
3. Go to Persona Bar > Manage > Sites

## Current result
Blank Sites page is displayed. Console errors are displayed "SCRIPT1002: Syntax error" and "SCRIPT5007: Unable to get property 'CommonReducers' of undefined or null reference"

## Expected result
Sites page should displayed without any error.

## Screenshots
![ie11-platform-sites-blankpage](https://user-images.githubusercontent.com/40901826/53942836-d4971080-40e1-11e9-83ff-277a6a5226e8.png)

## Error log
SCRIPT1002: Syntax error
SitesListView.js (1,15630)
SCRIPT5007: Unable to get property 'CommonReducers' of undefined or null reference
index.html (1,1251)
## Additional context
Add any other context about the bug that may be helpful for resolution.
## Affected version

* [x] 9.3.0
* [ ] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [x] Internet Explorer
* [ ] Edge

**Comment by bdukes** [comment]
I've verified this bug on my 9.3.0-RC2 site.

We probably need to apply the fix from #425 to the other modules

**Comment by valadas** [comment]
Merged
