### ISSUE TITLE
DNN Platform RC2 > Persona Bar > Settings > Scheduler > Add task UI issue in IE11

### ISSUE THREAD

**Issue by DinKumar** [dnnsoftware/Dnn.AdminExperience#429]
## Precondition
1. Install latest Platform RC Build
2. Host user credentials are available to access the application

## Description of bug
UI for adding task on Scheduler page is displayed as distorted in IE11 browser. 

## Steps to reproduce
1. Access DNN Platform application in IE11 browser.
2. Login as host user.
3. Go to Persona Bar > Settings > Scheduler  
4. Click on Scheduler tab
5. Click on Add Task link

## Current result
Screen displayed to add task is broken and user can not add task.

## Expected result
Add Task screen needs to be displayed with proper UI alignment. 

## Screenshots
![ie11-platform-scheduler-addtask](https://user-images.githubusercontent.com/40901826/53945854-90f3d500-40e8-11e9-836b-021c145e0161.png)

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] 9.3.0
* [ ] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [x] Internet Explorer
* [ ] Edge

**Comment by bdukes** [comment]
On first glance, this seems like an issue with flexbox, and so appears to be related to 265695f5270925cab44e849cabae101d4259f97c (cc @valadas).  Not sure what problem that commit was solving, and whether it might just be able to be reverted.

Note, while the UI is unusably small, it is possible to still use it to create a task, i.e. the functionality is not broken, only the styling.

**Comment by valadas** [comment]
If I remember correctly it was just to avoid huge unused spaced (paddings and margins) with the nesting of stuff or something along those lines. Or it was before a bug fix in the common component for the grids. I _think_ it could be reverted without much side effects.

**Comment by bdukes** [comment]
fix #433 merged
