### ISSUE TITLE
Create a module from manifest - An Unknown error has occurred.

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.AdminExperience#442]
Persona Bar > Extensions -> Create New Module -> Create new module from: Manifest -> Module Folder: select my module -> Resource: select the manifest. 
When I click install receive an error saying "**An Unknown error has occurred. Please check the admin logs for more information.**"

**Comment by valadas** [comment]
This duplicates #16

**Comment by valadas** [comment]
Oh, hold on, this one has a PR to it, let me close the other one instead...

**Comment by valadas** [comment]
Closing this issue since the PR is merged
