### ISSUE TITLE
Update login page

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.AdminExperience#5]
Dnn9 without updating the login and profile page is NOT complete, especially from a marketing perspective. The whole community would like to see these changes (actually now for years).Please update those pages.

Originally created by @kurtwilbies

**Comment by valadas** [comment]
I do not understand what you mean @kurtwilbies

**Comment by sleupold** [comment]
Login Page is not mobile friendly, same might apply to console module and user profile.

**Comment by valadas** [comment]
Closing this one as we have https://github.com/dnnsoftware/Dnn.Platform/issues/2471 and this is not part of the persona bar repository.
