### ISSUE TITLE
In 9.3.0 is not possible to edit LogSettings

### ISSUE THREAD

**Issue by ufoloko** [dnnsoftware/Dnn.AdminExperience#647]
## Description of bug
In version 9.3.0 is not possible to edit LogSettings, when click on pencil to edit, enable or disable a logtype, notthing happens

## Steps to reproduce
List the steps to reproduce the behavior:

Go to Admin Logs > Log Settings Tab and click in pencil from any item in list, nothing happens

## Current result
when click on pencil, nothing happens, you dont have any option to enable or disable logtype

## Expected result
It should be able to change LogType Settings, enable, disable, etc

![image](https://user-images.githubusercontent.com/1165122/55570025-37bb9900-56c8

## Affected version

* [x] DNN 9.3.0 an newer

All browser

**Comment by bdukes** [comment]
This appears to be an issue with the React Collapsible component used in that list.  The entry's edit view _is_ added to the DOM correctly, but it is hidden by a `height: 0` style on the `div` wrapping the `ReactCollapse--content` element.

**Comment by ufoloko** [comment]
Yes, is right, i can see the html code and rendered content for settings is there, editing with developer tools allows me to change height by auto and settings are there. Is there any way to solve with some code patch, till some solution is released?

**Comment by valadas** [comment]
PR Merged
