### ISSUE TITLE
Cannot create multiple root terms in hierarchical vocabulary

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.AdminExperience#69]
## Description of bug
When adding a term to a hierarchical vocabulary, the first term has no UI to select the parent (which is normal), but then for each new term, there is no way to not select a parent term so it is now impossible to have multiple root terms. This was previously possible in Dnn 8.0.4 and even 7.4.2.

## Steps to reproduce
List the steps to reproduce the behavior:
Got To Vocabularies, add a new vocabulary with hierarchical option.
Try to create a hierarchy such as this:
* Electronics
  * Televisions
  * Audio
* Computers
  * Systems
  * Components

## Current result
It is impossible in this example to create the computer branch, there is no UI to set no parent after the first term is created (televisions)

## Expected result
There should be a way to select no parent

## Screenshots
![image](https://user-images.githubusercontent.com/6371568/44997139-0f28c080-af7a-11e8-964a-3e19c9b6bbc1.png)

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
I doubt is is browser related

* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by bdukes** [comment]
AFAIK this has always been the case.  I would love to revamp Vocabularies and Terms to be simpler, so I'm happy to support this change, but I don't think this is a new bug in 9.x.

**Comment by valadas** [comment]
I am also not sure if it is new, but the versions I ticked are the ones I have tried it on.

**Comment by valadas** [comment]
Same for browsers, did not try them all, but I know it happens on Chrome (but probably not browser related)

**Comment by valadas** [comment]
I am closing this since it is currently by design and revamp this would be more involved in the platform than here.
