### ISSUE TITLE
Missing link class on inline help command links for clear-screen

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.AdminExperience#7]
### Description of Issue
The inline help command links are not styled correct and thus are very difficult to read.

![screencapture_ 2018-08-08 09 31 am _1794](https://user-images.githubusercontent.com/4568451/43847607-fd585788-9afe-11e8-8a3a-7f32ed952f54.png)

### Steps to Reproduce
- Install DNN 09.02.01
- Go to Settings > Prompt
- Type `help`
- View links for `clear-screen` command links

Originally created by @nvisionative at https://github.com/dnnsoftware/Dnn.AdminExperience.Extensions/issues/606

**Comment by david-poindexter** [comment]
Thanks for recreating the issue here @ohine - I'll resubmit a PR to this repo shortly.

**Comment by ohine** [comment]
Anytime! Thanks @nvisionative for getting this resubmitted too!
