### ISSUE TITLE
Tooltip not displayed under site link

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Dnn.AdminExperience#74]
## Description of bug
If you manage sites, there are 3 icons under the site URL for View Site, Site Settings, Export Template. The tooltip is not shown when the mouse in on the icon

## Steps to reproduce
List the steps to reproduce the behavior:
1. Login as Host
2. Use Personabar, Manage Sites
3. Hold your mouse in the cell with the site URL, icons appear
4. Move your mouse over an icon
5. The tooltip does **NOT** appear

## Current result
No tooltip

## Expected result
Show tooltip, this works in 9.2.0
Suggestion: do not hide the icons until the mouse is over the cell. This surprises the user.

## Screenshots
See attachment
![image](https://user-images.githubusercontent.com/5859855/45212799-1e6b7f00-b296-11e8-855a-3498f6f2149c.png)
![img_1076](https://user-images.githubusercontent.com/5859855/45212994-9afe5d80-b296-11e8-8474-0c929568f336.jpg)

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by Mhtshum** [comment]
It has been fixed in latest https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.3.0-rc0  build

**Comment by valadas** [comment]
I gonna keep this open as an improvement, I have no clue why icons are hidden, they should just show always IMO.

**Comment by valadas** [comment]
Recreated follow up issue in main repo at https://github.com/dnnsoftware/Dnn.Platform/issues/3064
