### ISSUE TITLE
Settings > Custom CSS: + character (adjacent sibling combinator) stripped out on save

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.AdminExperience#8]
## Steps to reproduce:
 
1. Visit PersonaBar > Settings > Custom CSS
2. Enter the following code: `.DnnModule + .DnnModule { margin-top: 1rem; }`
3. Press Save, and see the success message
4. Refresh the page
5. Visit PersonaBar > Settings > Custom CSS
6. You will see the code now says `.DnnModule   .DnnModule { margin-top: 1rem; }`

Note the `+` character (adjacent sibling combinator) has been replaced with a blank space character ` `.

## What should happen:

The `+` character should not be stripped out of the Custom CSS.

## Notes:

I'm using DNN Evoq Engage 9.2.0.

Tested in the latest versions of Firefox and Chrome on Windows Server 2016.

Originally created by @OllyHodgson at https://github.com/dnnsoftware/Dnn.AdminExperience.Extensions/issues/603

**Comment by valadas** [comment]
Able to reproduce in 9.3.0 RC0

**Comment by valadas** [comment]
PR Merged
