### ISSUE TITLE
About Screen - Evoq License Management and Not DNN Platform Info

### ISSUE THREAD

**Issue by mikesmeltzer** [dnnsoftware/Dnn.AdminExperience#81]
## Description of bug
The About screen located in Settings > About appears to be a license management screen for the commerical Evoq products.

Given that this is the DNN Platform, the About screen should have generic information regarding the DNN Platform and not commerical products.

## Steps to reproduce
1. Login to DNN
2. From the Persona Bar, hover over Settings
3. Select About

## Current result
Users of the DNN Platform are presented with an Evoq licensing screen.

## Expected result
Generic information regarding the DNN Platform.

Some types of information that could be displayed are:

- Current version / build info
- Links to current known issues for the version in question
- Links to the release notes for the version in question
- Links to the DNN documentation and help materials
- Etc.

## Affected version
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ x] 9.1
* [x ] 9.0

**Comment by OllyHodgson** [comment]
Should this screen exist at all in the non-commercial version of DNN? We can already hover the DNN logo to see the stuff you'd usually see in an About screen.

**Comment by OllyHodgson** [comment]
The discussion in https://github.com/dnnsoftware/Dnn.Platform/issues/2346 made me wonder about how we'd highlight new features (etc) after an upgrade. Wordpress has a panel which appears on the Dashboard after an upgrade, which tells the user what changed.

DNN doesn't really have the same kind of UI, so that wouldn't work - but maybe the About page could house the readme file for the release - explaining what's new / different / etc?

(and re-reading your bug, you've said all of that already!)

**Comment by mikesmeltzer** [comment]
Olly,

Good thoughts and glad we are aligned in our thinking.

DNN has a Getting Started modal window that you can pop which displays some info when a user logs in.  This might be a better way of highlighting to users that there was an update and here what was in the update.. Or at least to indicate to the user to go to the About screen for more details on what was updated or something..

That being said,  I feel that the About screen should have maybe a list of links to the release notes on GitHub for each release (could be dynamic) so that we don't need to remember to update it every release.

I think we are both saying:

1. The About screen currently is not proper for the Community version
2. The About screen should have some release note information about the current release or provide the user with a way (links or similar) to go get it

How do you feel about:

1. Links to the official community repository
2. Links to the official website
3. Links to the help documentation
4. Links to the official forums

Thoughts? Anything missing above?

**Comment by OllyHodgson** [comment]
Oh yes, I've seen the Getting Started modal in Evoq - I assumed it was an Evoq-only feature. Does it appear after an upgrade, or only on a fresh install?

Your list sounds great. I'd probably add a link to the release notes for the version the user is running (e.g.  https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.2.2) or the latest version (https://github.com/dnnsoftware/Dnn.Platform/releases/latest - assuming that always points to the lastest _stable_ release)

**Comment by sleupold** [comment]
We used to have a list of new features in "Whats New" module in DNN 5 to DNN 7.
Re-Adding this list with a resource key for each version is not very helpful IMO.
I would prefer a link to a web page, where this information may be found easily (just including new features from current version is not very helpful, as many instances are not upgrading to every version)

**Comment by mikesmeltzer** [comment]
I think the next step is to do up a rough mock-up identifying the functionality, what web page it links to, etc. so that someone could pick this up and work on it.  I can do this over the coming weeks unless someone else wants to pick it up in the meantime.

**Comment by mikesmeltzer** [comment]
Another issue on this topic can be found at https://github.com/dnnsoftware/Dnn.Platform/issues/2865.

**Comment by Timo-Breumelhof** [comment]
Can I add: Can we please move restart application and clear cache here? It drivesme nuts that they are so hidden right now..

![image](https://user-images.githubusercontent.com/8999382/62351651-6c205400-b506-11e9-919b-7eff1c6b8e3d.png)

**Comment by david-poindexter** [comment]
> Can I add: Can we please move restart application and clear cache here? It drivesme nuts that they are so hidden right now..
> 
> ![image](https://user-images.githubusercontent.com/8999382/62351651-6c205400-b506-11e9-919b-7eff1c6b8e3d.png)

@Timo-Breumelhof that sounds like a great new issue.  I agree that needs some conversation to determine the right place for those features.

**Comment by Timo-Breumelhof** [comment]
@david-poindexter https://github.com/dnnsoftware/Dnn.AdminExperience/issues/1084

**Comment by valadas** [comment]
Closing since merged
