### ISSUE TITLE
open page settings can't display data for correct page

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.AdminExperience#845]
## Description of bug
open page settings can't display data for the correct page

## Steps to reproduce
1. install 9.3.0 latest build and login as host; 
2. open Settings > Site Settings > Languages in PB, add a new language, enable content localization; 
3. edit the pages for the new language, click "view page settings" for any page except home page;

## Current result
the page details form will show data for the home page, but not the selected page.

## Expected result
the page details form should show data for the selected page.

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1

**Comment by sleupold** [comment]
please adjust version affected, thank you

**Comment by valadas** [comment]
I cannot reproduce in 9.4.0 RC, @zyhfish if you can still reproduce in current releases, please open a new issue.
