### ISSUE TITLE
UX: "It appears you have a slow connection..." is misleading

### ISSUE THREAD

**Issue by OllyHodgson** [dnnsoftware/Dnn.AdminExperience#90]
## Description of bug
During long running operations, DNN will show a "It appears you have a slow connection... We are processing your content" message. Almost every time I've encountered this, it's been due to DNN taking a long time to process a complex request.

I suggest the language is changed to something closer to the truth, e.g. "This task is taking a while. We are still processing your content". Or it could just be reduced to "We are processing your content".

## Steps to reproduce
Do anything which will cause a long-running request in the PersonaBar. For example:

1. PersonaBar > Content > Pages
2. Add Multiple Pages
3. Paste in a list of 100 page titles to add
4. Click Add Pages

## Current result
After a while the user is shown a "It appears you have a slow connection... We are processing your content" message.

## Expected result
DNN doesn't blame the user's connection for its own slow response.

## Screenshots
![image](https://user-images.githubusercontent.com/437224/46008230-109a6400-c0b4-11e8-8981-b773a2717e27.png)

## Additional context
Whatever message is chosen, I imagine it will need to be translated.

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser
n/a

**Comment by valadas** [comment]
I am all for the simplest, that message bothers me a lot too. When doing a restart for instance, it is not processing any *content*. Just "Processing..." would be totally fine in my opinion.
