### ISSUE TITLE
SQL console not working

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.AdminExperience#971]
## Description of bug
The sql console is not working.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to SQL Console
2. Notice red error on top of the module
3. Open browser developer tools
4. Notice javascript error

## Current result
Errors and is unusable

## Expected result
Should work

## Screenshots
![image](https://user-images.githubusercontent.com/6371568/58441588-3e0b3780-80b1-11e9-8f7d-653daad918cf.png)

## Additional context
This may be related to either the combining of the PB Libraries into one or the PetaPoco issue https://github.com/dnnsoftware/Dnn.Platform/pull/2817
I have not investigated yet, just wanted to log it to make sure we get to it before 9.4 is out since this is a regression

## Affected version

* [x] 9.4.0 Alpha (35)
* [ ] 9.3.2
* [ ] 9.3.1
* [ ] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
Tried chrome only but probably not browser related

* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by donker** [comment]
Looks like a PetaPoco error:

System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Invalid object name 'SqlQuery'.

This happens when doing a Get() on the SqlQuery repository.

**Comment by donker** [comment]
I have no clue how the PetaPoco integration works ... I'd need to dig deeper.

One thing I noticed is that instead of using NuGet PetaPoco.Compiled we're using a ref to a dll. Was that intentional?

**Comment by donker** [comment]
So DNN's IMapper is not being passed into the construction of the database. I can't tell if this was a change in PetaPoco or DNN. I'll have a PR soon.

**Comment by valadas** [comment]
I can confirm it works with the previous fix to PetaPoco https://github.com/dnnsoftware/Dnn.Platform/pull/2817 also fixed this issue.

I leave this open to see which solution we keep but yeah, that was the cause of this issue.

**Comment by valadas** [comment]
Ok, this is resolved by the merged pr, the other one is basically a duplicate
