### ISSUE TITLE
Update Security Analyzer to show a warning for RichText profile properties

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.AdminExperience#98]
## Description of problem
Currently the security analyzer flags the Biography field as an failure due to it's default configuration of being a rich text field. 

## Description of solution
We need to switch this to a warning, maybe update the steps to include a bit more details on where to go and change this to a basic text input.

**Comment by valadas** [comment]
@dnnsoftware/tag Do we want to just change the UI to a warning and info or do we want to also make the Biography field a multiline instead of html by default on new installs?

**Comment by sleupold** [comment]
Usually, a site should not issue a warning by default, but we are having script filter in place and there are many use cases, where rich text for bio makes sense.

**Comment by valadas** [comment]
PR Merged
