### ISSUE TITLE
Persona Bar modules do not work on upgrade

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.AdminExperience#981]
## Description of bug
Almost all extensions are missing after upgrading. (except site assets and global assets)

## Steps to reproduce
List the steps to reproduce the behavior:
1. Install Dnn 9.3.2
2. Upgrade to Dnn 9.4.0 alpha

## Current result
Most persona bar modules are missing

## Expected result
All modules should still exist

## Additional context
The upgrade should uninstall all persona bar modules and then reinstall them.

## Affected version

* [x] 9.4.0 only when upgrading

**Comment by bdukes** [comment]
No major surprises, but I've verified this is also an issue when upgrading from 9.1.1, and is _not_ an issue when upgrading from 8.0.4

**Comment by valadas** [comment]
I am starting to take a look at this now...
