### ISSUE TITLE
Group old and new privacy related settings in new tab on Site Settings

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.AdminExperience#99]
## Description of problem
We need to be transparent and up front about what DNN is doing in terms of privacy and offer admins the best possible info and options to make the best decisions.

There are now 5 tabs under "Site Behavior": Default Pages, Messaging, User Profiles, Site Aliases, More. Under More you'll find:
- Check for Software Upgrades
- Participate in DNN Improvement Program
These settings have an impact on privacy and security.

There are settings that are currently not yet in the UI (Show Copyright Notice) or that will be implemented shortly for GDPR (strategies surrounding user deletion, cookie consent, etc). These settings also need to find a place in the UI.

## Description of solution
Create a new tab "Privacy" under site behavior. This will hold the existing settings regarding privacy and the future ones we create. It will provide a single home for admins to check all privacy settings.

**Comment by sleupold** [comment]
There are a couple more settings affecting privacy, like default visibility of profile properties, registration and de-registration etc. I suggest not to duplicate those settings (it was one idea of the persona bar removing duplicate settings), but providing a link to these settings.

**Comment by trouble2** [comment]
Couldn't you call this something like 'Standards' so this would be a more generic title for settings/information about conforming to different standards, like 'GDPR', 'Section 508' and whatever more web standards are out there....

**Comment by mitchelsellers** [comment]
Can we add update service to this. Including a default unchecked

**Comment by donker** [comment]
Yes, I intended to.

**Comment by donker** [comment]
> 
> 
> Couldn't you call this something like 'Standards' so this would be a more generic title for settings/information about conforming to different standards, like 'GDPR', 'Section 508' and whatever more web standards are out there....

It needs to be clear what it is though. For me any admin (new or experienced) should intuitively know where they can find these settings. That is why I went for the more common term. "Privacy" or "Security" will be very clear in what you can find there.

**Comment by donker** [comment]
> 
> 
> Can we add update service to this. Including a default unchecked

I intended to, and also to provide better feedback about what it actually does. This may be a hot political potato, but I think we owe it to our audience to be clear and up front about what these settings do so they can make an informed decision. Maybe we'd add a link to a wiki page to make sure people have everything they need to know.

**Comment by sleupold** [comment]
>           Couldn't you call this something like 'Standards' so this would be a more generic title for settings/information about conforming to different standards, like 'GDPR', 'Section 508' and whatever more web standards are out there....

GDPR is not a standard, it is a legal requirement on Privacy of personal data. IMO "Privacy" is the clearest term for it.
Accessibility would be another one.

**Comment by OllyHodgson** [comment]
@donker JFYI, the "Show Copyright Credits" is presently under Settings > Security > More > More Security Settings.

**Comment by valadas** [comment]
I think this is complete and will close, if I am wrong please open an issue from what is left to do:

![image](https://user-images.githubusercontent.com/6371568/51511413-38ce7100-1dcf-11e9-817a-6e44eb7b5483.png)
